// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _axis2xfMat_HH_
#define _axis2xfMat_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct axis2xfMat : public sc_module {
    // Port declarations 28
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<24> > src_TDATA;
    sc_in< sc_logic > src_TVALID;
    sc_out< sc_logic > src_TREADY;
    sc_out< sc_lv<8> > p_src_data_V_din;
    sc_in< sc_logic > p_src_data_V_full_n;
    sc_out< sc_logic > p_src_data_V_write;
    sc_in< sc_lv<12> > src_rows_cast1_loc_dout;
    sc_in< sc_logic > src_rows_cast1_loc_empty_n;
    sc_out< sc_logic > src_rows_cast1_loc_read;
    sc_in< sc_lv<12> > src_cols_cast2_loc_dout;
    sc_in< sc_logic > src_cols_cast2_loc_empty_n;
    sc_out< sc_logic > src_cols_cast2_loc_read;
    sc_out< sc_lv<12> > src_rows_cast1_loc_out_din;
    sc_in< sc_logic > src_rows_cast1_loc_out_full_n;
    sc_out< sc_logic > src_rows_cast1_loc_out_write;
    sc_out< sc_lv<12> > src_cols_cast2_loc_out_din;
    sc_in< sc_logic > src_cols_cast2_loc_out_full_n;
    sc_out< sc_logic > src_cols_cast2_loc_out_write;


    // Module declarations
    axis2xfMat(sc_module_name name);
    SC_HAS_PROCESS(axis2xfMat);

    ~axis2xfMat();

    sc_trace_file* mVcdFile;

    regslice_both<24>* regslice_both_src_data_V_U;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > src_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln10_fu_134_p2;
    sc_signal< sc_logic > p_src_data_V_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > icmp_ln10_reg_168;
    sc_signal< sc_logic > src_rows_cast1_loc_blk_n;
    sc_signal< sc_logic > src_cols_cast2_loc_blk_n;
    sc_signal< sc_logic > src_rows_cast1_loc_out_blk_n;
    sc_signal< sc_logic > src_cols_cast2_loc_out_blk_n;
    sc_signal< sc_lv<12> > j_0_i_i_reg_112;
    sc_signal< sc_lv<12> > src_rows_cast1_loc_r_reg_149;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<12> > src_cols_cast2_loc_r_reg_154;
    sc_signal< sc_lv<1> > icmp_ln9_fu_123_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<12> > i_fu_128_p2;
    sc_signal< sc_lv<12> > i_reg_163;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<12> > j_fu_139_p2;
    sc_signal< sc_lv<8> > trunc_ln209_fu_145_p1;
    sc_signal< sc_lv<8> > trunc_ln209_reg_177;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state3;
    sc_signal< sc_lv<12> > i_0_i_i_reg_101;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_logic > regslice_both_src_data_V_U_apdone_blk;
    sc_signal< sc_lv<24> > src_TDATA_int;
    sc_signal< sc_logic > src_TVALID_int;
    sc_signal< sc_logic > src_TREADY_int;
    sc_signal< sc_logic > regslice_both_src_data_V_U_ack_in;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_pp0_stage0;
    static const sc_lv<4> ap_ST_fsm_state5;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<12> ap_const_lv12_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state3_pp0_stage0_iter0();
    void thread_ap_block_state4_pp0_stage0_iter1();
    void thread_ap_condition_pp0_exit_iter0_state3();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_i_fu_128_p2();
    void thread_icmp_ln10_fu_134_p2();
    void thread_icmp_ln9_fu_123_p2();
    void thread_internal_ap_ready();
    void thread_j_fu_139_p2();
    void thread_p_src_data_V_blk_n();
    void thread_p_src_data_V_din();
    void thread_p_src_data_V_write();
    void thread_real_start();
    void thread_src_TDATA_blk_n();
    void thread_src_TREADY();
    void thread_src_TREADY_int();
    void thread_src_cols_cast2_loc_blk_n();
    void thread_src_cols_cast2_loc_out_blk_n();
    void thread_src_cols_cast2_loc_out_din();
    void thread_src_cols_cast2_loc_out_write();
    void thread_src_cols_cast2_loc_read();
    void thread_src_rows_cast1_loc_blk_n();
    void thread_src_rows_cast1_loc_out_blk_n();
    void thread_src_rows_cast1_loc_out_din();
    void thread_src_rows_cast1_loc_out_write();
    void thread_src_rows_cast1_loc_read();
    void thread_start_out();
    void thread_start_write();
    void thread_trunc_ln209_fu_145_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
