// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "axis2xfMat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic axis2xfMat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic axis2xfMat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> axis2xfMat::ap_ST_fsm_state1 = "1";
const sc_lv<4> axis2xfMat::ap_ST_fsm_state2 = "10";
const sc_lv<4> axis2xfMat::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> axis2xfMat::ap_ST_fsm_state5 = "1000";
const bool axis2xfMat::ap_const_boolean_1 = true;
const sc_lv<32> axis2xfMat::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> axis2xfMat::ap_const_lv32_2 = "10";
const bool axis2xfMat::ap_const_boolean_0 = false;
const sc_lv<1> axis2xfMat::ap_const_lv1_0 = "0";
const sc_lv<32> axis2xfMat::ap_const_lv32_1 = "1";
const sc_lv<1> axis2xfMat::ap_const_lv1_1 = "1";
const sc_lv<12> axis2xfMat::ap_const_lv12_0 = "000000000000";
const sc_lv<32> axis2xfMat::ap_const_lv32_3 = "11";
const sc_lv<12> axis2xfMat::ap_const_lv12_1 = "1";

axis2xfMat::axis2xfMat(sc_module_name name) : sc_module(name), mVcdFile(0) {
    regslice_both_src_data_V_U = new regslice_both<24>("regslice_both_src_data_V_U");
    regslice_both_src_data_V_U->ap_clk(ap_clk);
    regslice_both_src_data_V_U->ap_rst(ap_rst);
    regslice_both_src_data_V_U->data_in(src_TDATA);
    regslice_both_src_data_V_U->vld_in(src_TVALID);
    regslice_both_src_data_V_U->ack_in(regslice_both_src_data_V_U_ack_in);
    regslice_both_src_data_V_U->data_out(src_TDATA_int);
    regslice_both_src_data_V_U->vld_out(src_TVALID_int);
    regslice_both_src_data_V_U->ack_out(src_TREADY_int);
    regslice_both_src_data_V_U->apdone_blk(regslice_both_src_data_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( p_src_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln10_fu_134_p2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln10_reg_168 );
    sensitive << ( src_TVALID_int );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( p_src_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln10_fu_134_p2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln10_reg_168 );
    sensitive << ( src_TVALID_int );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( p_src_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln10_fu_134_p2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln10_reg_168 );
    sensitive << ( src_TVALID_int );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( src_rows_cast1_loc_empty_n );
    sensitive << ( src_cols_cast2_loc_empty_n );
    sensitive << ( src_rows_cast1_loc_out_full_n );
    sensitive << ( src_cols_cast2_loc_out_full_n );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);
    sensitive << ( icmp_ln10_fu_134_p2 );
    sensitive << ( src_TVALID_int );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( p_src_data_V_full_n );
    sensitive << ( icmp_ln10_reg_168 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln10_fu_134_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln9_fu_123_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_i_fu_128_p2);
    sensitive << ( i_0_i_i_reg_101 );

    SC_METHOD(thread_icmp_ln10_fu_134_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( j_0_i_i_reg_112 );
    sensitive << ( src_cols_cast2_loc_r_reg_154 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln9_fu_123_p2);
    sensitive << ( src_rows_cast1_loc_r_reg_149 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_i_i_reg_101 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( icmp_ln9_fu_123_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j_fu_139_p2);
    sensitive << ( j_0_i_i_reg_112 );

    SC_METHOD(thread_p_src_data_V_blk_n);
    sensitive << ( p_src_data_V_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln10_reg_168 );

    SC_METHOD(thread_p_src_data_V_din);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln10_reg_168 );
    sensitive << ( trunc_ln209_reg_177 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_p_src_data_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln10_reg_168 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_src_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln10_fu_134_p2 );
    sensitive << ( src_TVALID_int );

    SC_METHOD(thread_src_TREADY);
    sensitive << ( src_TVALID );
    sensitive << ( regslice_both_src_data_V_U_ack_in );

    SC_METHOD(thread_src_TREADY_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln10_fu_134_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_src_cols_cast2_loc_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_cols_cast2_loc_empty_n );

    SC_METHOD(thread_src_cols_cast2_loc_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_cols_cast2_loc_out_full_n );

    SC_METHOD(thread_src_cols_cast2_loc_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_empty_n );
    sensitive << ( src_cols_cast2_loc_dout );
    sensitive << ( src_cols_cast2_loc_empty_n );
    sensitive << ( src_rows_cast1_loc_out_full_n );
    sensitive << ( src_cols_cast2_loc_out_full_n );

    SC_METHOD(thread_src_cols_cast2_loc_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_empty_n );
    sensitive << ( src_cols_cast2_loc_empty_n );
    sensitive << ( src_rows_cast1_loc_out_full_n );
    sensitive << ( src_cols_cast2_loc_out_full_n );

    SC_METHOD(thread_src_cols_cast2_loc_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_empty_n );
    sensitive << ( src_cols_cast2_loc_empty_n );
    sensitive << ( src_rows_cast1_loc_out_full_n );
    sensitive << ( src_cols_cast2_loc_out_full_n );

    SC_METHOD(thread_src_rows_cast1_loc_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_empty_n );

    SC_METHOD(thread_src_rows_cast1_loc_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_out_full_n );

    SC_METHOD(thread_src_rows_cast1_loc_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_dout );
    sensitive << ( src_rows_cast1_loc_empty_n );
    sensitive << ( src_cols_cast2_loc_empty_n );
    sensitive << ( src_rows_cast1_loc_out_full_n );
    sensitive << ( src_cols_cast2_loc_out_full_n );

    SC_METHOD(thread_src_rows_cast1_loc_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_empty_n );
    sensitive << ( src_cols_cast2_loc_empty_n );
    sensitive << ( src_rows_cast1_loc_out_full_n );
    sensitive << ( src_cols_cast2_loc_out_full_n );

    SC_METHOD(thread_src_rows_cast1_loc_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_empty_n );
    sensitive << ( src_cols_cast2_loc_empty_n );
    sensitive << ( src_rows_cast1_loc_out_full_n );
    sensitive << ( src_cols_cast2_loc_out_full_n );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_trunc_ln209_fu_145_p1);
    sensitive << ( src_TDATA_int );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_rows_cast1_loc_empty_n );
    sensitive << ( src_cols_cast2_loc_empty_n );
    sensitive << ( src_rows_cast1_loc_out_full_n );
    sensitive << ( src_cols_cast2_loc_out_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln10_fu_134_p2 );
    sensitive << ( icmp_ln9_fu_123_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "axis2xfMat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, src_TDATA, "(port)src_TDATA");
    sc_trace(mVcdFile, src_TVALID, "(port)src_TVALID");
    sc_trace(mVcdFile, src_TREADY, "(port)src_TREADY");
    sc_trace(mVcdFile, p_src_data_V_din, "(port)p_src_data_V_din");
    sc_trace(mVcdFile, p_src_data_V_full_n, "(port)p_src_data_V_full_n");
    sc_trace(mVcdFile, p_src_data_V_write, "(port)p_src_data_V_write");
    sc_trace(mVcdFile, src_rows_cast1_loc_dout, "(port)src_rows_cast1_loc_dout");
    sc_trace(mVcdFile, src_rows_cast1_loc_empty_n, "(port)src_rows_cast1_loc_empty_n");
    sc_trace(mVcdFile, src_rows_cast1_loc_read, "(port)src_rows_cast1_loc_read");
    sc_trace(mVcdFile, src_cols_cast2_loc_dout, "(port)src_cols_cast2_loc_dout");
    sc_trace(mVcdFile, src_cols_cast2_loc_empty_n, "(port)src_cols_cast2_loc_empty_n");
    sc_trace(mVcdFile, src_cols_cast2_loc_read, "(port)src_cols_cast2_loc_read");
    sc_trace(mVcdFile, src_rows_cast1_loc_out_din, "(port)src_rows_cast1_loc_out_din");
    sc_trace(mVcdFile, src_rows_cast1_loc_out_full_n, "(port)src_rows_cast1_loc_out_full_n");
    sc_trace(mVcdFile, src_rows_cast1_loc_out_write, "(port)src_rows_cast1_loc_out_write");
    sc_trace(mVcdFile, src_cols_cast2_loc_out_din, "(port)src_cols_cast2_loc_out_din");
    sc_trace(mVcdFile, src_cols_cast2_loc_out_full_n, "(port)src_cols_cast2_loc_out_full_n");
    sc_trace(mVcdFile, src_cols_cast2_loc_out_write, "(port)src_cols_cast2_loc_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, src_TDATA_blk_n, "src_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln10_fu_134_p2, "icmp_ln10_fu_134_p2");
    sc_trace(mVcdFile, p_src_data_V_blk_n, "p_src_data_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, icmp_ln10_reg_168, "icmp_ln10_reg_168");
    sc_trace(mVcdFile, src_rows_cast1_loc_blk_n, "src_rows_cast1_loc_blk_n");
    sc_trace(mVcdFile, src_cols_cast2_loc_blk_n, "src_cols_cast2_loc_blk_n");
    sc_trace(mVcdFile, src_rows_cast1_loc_out_blk_n, "src_rows_cast1_loc_out_blk_n");
    sc_trace(mVcdFile, src_cols_cast2_loc_out_blk_n, "src_cols_cast2_loc_out_blk_n");
    sc_trace(mVcdFile, j_0_i_i_reg_112, "j_0_i_i_reg_112");
    sc_trace(mVcdFile, src_rows_cast1_loc_r_reg_149, "src_rows_cast1_loc_r_reg_149");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, src_cols_cast2_loc_r_reg_154, "src_cols_cast2_loc_r_reg_154");
    sc_trace(mVcdFile, icmp_ln9_fu_123_p2, "icmp_ln9_fu_123_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_128_p2, "i_fu_128_p2");
    sc_trace(mVcdFile, i_reg_163, "i_reg_163");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, j_fu_139_p2, "j_fu_139_p2");
    sc_trace(mVcdFile, trunc_ln209_fu_145_p1, "trunc_ln209_fu_145_p1");
    sc_trace(mVcdFile, trunc_ln209_reg_177, "trunc_ln209_reg_177");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, i_0_i_i_reg_101, "i_0_i_i_reg_101");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, regslice_both_src_data_V_U_apdone_blk, "regslice_both_src_data_V_U_apdone_blk");
    sc_trace(mVcdFile, src_TDATA_int, "src_TDATA_int");
    sc_trace(mVcdFile, src_TVALID_int, "src_TVALID_int");
    sc_trace(mVcdFile, src_TREADY_int, "src_TREADY_int");
    sc_trace(mVcdFile, regslice_both_src_data_V_U_ack_in, "regslice_both_src_data_V_U_ack_in");
#endif

    }
}

axis2xfMat::~axis2xfMat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete regslice_both_src_data_V_U;
}

void axis2xfMat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln9_fu_123_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_123_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_123_p2.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_0_i_i_reg_101 = i_reg_163.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_out_full_n.read())))) {
        i_0_i_i_reg_101 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_123_p2.read()))) {
        j_0_i_i_reg_112 = ap_const_lv12_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        j_0_i_i_reg_112 = j_fu_139_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_163 = i_fu_128_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln10_reg_168 = icmp_ln10_fu_134_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_out_full_n.read())))) {
        src_cols_cast2_loc_r_reg_154 = src_cols_cast2_loc_dout.read();
        src_rows_cast1_loc_r_reg_149 = src_rows_cast1_loc_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        trunc_ln209_reg_177 = trunc_ln209_fu_145_p1.read();
    }
}

void axis2xfMat::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void axis2xfMat::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void axis2xfMat::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void axis2xfMat::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void axis2xfMat::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void axis2xfMat::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_168.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_V_full_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_TVALID_int.read())));
}

void axis2xfMat::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_168.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_V_full_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_TVALID_int.read())));
}

void axis2xfMat::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_168.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_V_full_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_TVALID_int.read())));
}

void axis2xfMat::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_out_full_n.read()));
}

void axis2xfMat::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = (esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_TVALID_int.read()));
}

void axis2xfMat::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_168.read()) && esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_V_full_n.read()));
}

void axis2xfMat::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void axis2xfMat::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln9_fu_123_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void axis2xfMat::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void axis2xfMat::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void axis2xfMat::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void axis2xfMat::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void axis2xfMat::thread_i_fu_128_p2() {
    i_fu_128_p2 = (!i_0_i_i_reg_101.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(i_0_i_i_reg_101.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void axis2xfMat::thread_icmp_ln10_fu_134_p2() {
    icmp_ln10_fu_134_p2 = (!j_0_i_i_reg_112.read().is_01() || !src_cols_cast2_loc_r_reg_154.read().is_01())? sc_lv<1>(): sc_lv<1>(j_0_i_i_reg_112.read() == src_cols_cast2_loc_r_reg_154.read());
}

void axis2xfMat::thread_icmp_ln9_fu_123_p2() {
    icmp_ln9_fu_123_p2 = (!i_0_i_i_reg_101.read().is_01() || !src_rows_cast1_loc_r_reg_149.read().is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_i_reg_101.read() == src_rows_cast1_loc_r_reg_149.read());
}

void axis2xfMat::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln9_fu_123_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void axis2xfMat::thread_j_fu_139_p2() {
    j_fu_139_p2 = (!j_0_i_i_reg_112.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(j_0_i_i_reg_112.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void axis2xfMat::thread_p_src_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_168.read()))) {
        p_src_data_V_blk_n = p_src_data_V_full_n.read();
    } else {
        p_src_data_V_blk_n = ap_const_logic_1;
    }
}

void axis2xfMat::thread_p_src_data_V_din() {
    p_src_data_V_din = trunc_ln209_reg_177.read();
}

void axis2xfMat::thread_p_src_data_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_168.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_src_data_V_write = ap_const_logic_1;
    } else {
        p_src_data_V_write = ap_const_logic_0;
    }
}

void axis2xfMat::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void axis2xfMat::thread_src_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_0))) {
        src_TDATA_blk_n = src_TVALID_int.read();
    } else {
        src_TDATA_blk_n = ap_const_logic_1;
    }
}

void axis2xfMat::thread_src_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, src_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_src_data_V_U_ack_in.read()))) {
        src_TREADY = ap_const_logic_1;
    } else {
        src_TREADY = ap_const_logic_0;
    }
}

void axis2xfMat::thread_src_TREADY_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        src_TREADY_int = ap_const_logic_1;
    } else {
        src_TREADY_int = ap_const_logic_0;
    }
}

void axis2xfMat::thread_src_cols_cast2_loc_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        src_cols_cast2_loc_blk_n = src_cols_cast2_loc_empty_n.read();
    } else {
        src_cols_cast2_loc_blk_n = ap_const_logic_1;
    }
}

void axis2xfMat::thread_src_cols_cast2_loc_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        src_cols_cast2_loc_out_blk_n = src_cols_cast2_loc_out_full_n.read();
    } else {
        src_cols_cast2_loc_out_blk_n = ap_const_logic_1;
    }
}

void axis2xfMat::thread_src_cols_cast2_loc_out_din() {
    src_cols_cast2_loc_out_din = src_cols_cast2_loc_dout.read();
}

void axis2xfMat::thread_src_cols_cast2_loc_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_out_full_n.read())))) {
        src_cols_cast2_loc_out_write = ap_const_logic_1;
    } else {
        src_cols_cast2_loc_out_write = ap_const_logic_0;
    }
}

void axis2xfMat::thread_src_cols_cast2_loc_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_out_full_n.read())))) {
        src_cols_cast2_loc_read = ap_const_logic_1;
    } else {
        src_cols_cast2_loc_read = ap_const_logic_0;
    }
}

void axis2xfMat::thread_src_rows_cast1_loc_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        src_rows_cast1_loc_blk_n = src_rows_cast1_loc_empty_n.read();
    } else {
        src_rows_cast1_loc_blk_n = ap_const_logic_1;
    }
}

void axis2xfMat::thread_src_rows_cast1_loc_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        src_rows_cast1_loc_out_blk_n = src_rows_cast1_loc_out_full_n.read();
    } else {
        src_rows_cast1_loc_out_blk_n = ap_const_logic_1;
    }
}

void axis2xfMat::thread_src_rows_cast1_loc_out_din() {
    src_rows_cast1_loc_out_din = src_rows_cast1_loc_dout.read();
}

void axis2xfMat::thread_src_rows_cast1_loc_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_out_full_n.read())))) {
        src_rows_cast1_loc_out_write = ap_const_logic_1;
    } else {
        src_rows_cast1_loc_out_write = ap_const_logic_0;
    }
}

void axis2xfMat::thread_src_rows_cast1_loc_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_out_full_n.read())))) {
        src_rows_cast1_loc_read = ap_const_logic_1;
    } else {
        src_rows_cast1_loc_read = ap_const_logic_0;
    }
}

void axis2xfMat::thread_start_out() {
    start_out = real_start.read();
}

void axis2xfMat::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void axis2xfMat::thread_trunc_ln209_fu_145_p1() {
    trunc_ln209_fu_145_p1 = src_TDATA_int.read().range(8-1, 0);
}

void axis2xfMat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_rows_cast1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, src_cols_cast2_loc_out_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln9_fu_123_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln10_fu_134_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

