// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _fast_HH_
#define _fast_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "xFFastCornerDetectio.h"

namespace ap_rtl {

struct fast : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > p_src_mat_rows_dout;
    sc_in< sc_logic > p_src_mat_rows_empty_n;
    sc_out< sc_logic > p_src_mat_rows_read;
    sc_in< sc_lv<32> > p_src_mat_cols_dout;
    sc_in< sc_logic > p_src_mat_cols_empty_n;
    sc_out< sc_logic > p_src_mat_cols_read;
    sc_in< sc_lv<8> > p_src_mat_data_V_dout;
    sc_in< sc_logic > p_src_mat_data_V_empty_n;
    sc_out< sc_logic > p_src_mat_data_V_read;
    sc_out< sc_lv<1> > p_dst_mat_data_V_din;
    sc_in< sc_logic > p_dst_mat_data_V_full_n;
    sc_out< sc_logic > p_dst_mat_data_V_write;
    sc_in< sc_lv<32> > threshold_dout;
    sc_in< sc_logic > threshold_empty_n;
    sc_out< sc_logic > threshold_read;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    fast(sc_module_name name);
    SC_HAS_PROCESS(fast);

    ~fast();

    sc_trace_file* mVcdFile;

    xFFastCornerDetectio* grp_xFFastCornerDetectio_fu_46;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > p_src_mat_rows_blk_n;
    sc_signal< sc_logic > p_src_mat_cols_blk_n;
    sc_signal< sc_logic > threshold_blk_n;
    sc_signal< sc_lv<8> > trunc_ln68_fu_57_p1;
    sc_signal< sc_lv<8> > trunc_ln68_reg_72;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<16> > trunc_ln946_fu_62_p1;
    sc_signal< sc_lv<16> > trunc_ln946_reg_77;
    sc_signal< sc_lv<16> > trunc_ln946_1_fu_67_p1;
    sc_signal< sc_lv<16> > trunc_ln946_1_reg_82;
    sc_signal< sc_logic > grp_xFFastCornerDetectio_fu_46_p_src_mat_data_V_read;
    sc_signal< sc_lv<1> > grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_din;
    sc_signal< sc_logic > grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_write;
    sc_signal< sc_logic > grp_xFFastCornerDetectio_fu_46_ap_start;
    sc_signal< sc_logic > grp_xFFastCornerDetectio_fu_46_ap_done;
    sc_signal< sc_logic > grp_xFFastCornerDetectio_fu_46_ap_ready;
    sc_signal< sc_logic > grp_xFFastCornerDetectio_fu_46_ap_idle;
    sc_signal< sc_logic > grp_xFFastCornerDetectio_fu_46_ap_continue;
    sc_signal< sc_logic > grp_xFFastCornerDetectio_fu_46_ap_start_reg;
    sc_signal< bool > ap_block_state1_ignore_call11;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_sync_grp_xFFastCornerDetectio_fu_46_ap_ready;
    sc_signal< sc_logic > ap_sync_grp_xFFastCornerDetectio_fu_46_ap_done;
    sc_signal< bool > ap_block_state2_on_subcall_done;
    sc_signal< sc_logic > ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_ready;
    sc_signal< sc_logic > ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_done;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state1();
    void thread_ap_block_state1_ignore_call11();
    void thread_ap_block_state2_on_subcall_done();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_grp_xFFastCornerDetectio_fu_46_ap_done();
    void thread_ap_sync_grp_xFFastCornerDetectio_fu_46_ap_ready();
    void thread_grp_xFFastCornerDetectio_fu_46_ap_continue();
    void thread_grp_xFFastCornerDetectio_fu_46_ap_start();
    void thread_p_dst_mat_data_V_din();
    void thread_p_dst_mat_data_V_write();
    void thread_p_src_mat_cols_blk_n();
    void thread_p_src_mat_cols_read();
    void thread_p_src_mat_data_V_read();
    void thread_p_src_mat_rows_blk_n();
    void thread_p_src_mat_rows_read();
    void thread_threshold_blk_n();
    void thread_threshold_read();
    void thread_trunc_ln68_fu_57_p1();
    void thread_trunc_ln946_1_fu_67_p1();
    void thread_trunc_ln946_fu_62_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
