// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fast_accel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int fast_accel::C_S_AXI_DATA_WIDTH = "100000";
const int fast_accel::C_S_AXI_WSTRB_WIDTH = "100";
const int fast_accel::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic fast_accel::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<24> fast_accel::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<1> fast_accel::ap_const_lv1_0 = "0";
const sc_logic fast_accel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> fast_accel::ap_const_lv2_0 = "00";
const sc_lv<2> fast_accel::ap_const_lv2_1 = "1";
const bool fast_accel::ap_const_boolean_1 = true;

fast_accel::fast_accel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fast_accel_AXILiteS_s_axi_U = new fast_accel_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("fast_accel_AXILiteS_s_axi_U");
    fast_accel_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    fast_accel_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    fast_accel_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    fast_accel_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    fast_accel_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    fast_accel_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    fast_accel_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    fast_accel_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    fast_accel_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    fast_accel_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    fast_accel_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    fast_accel_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    fast_accel_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    fast_accel_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    fast_accel_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    fast_accel_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    fast_accel_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    fast_accel_AXILiteS_s_axi_U->ACLK(ap_clk);
    fast_accel_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    fast_accel_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    fast_accel_AXILiteS_s_axi_U->src_rows(src_rows);
    fast_accel_AXILiteS_s_axi_U->src_cols(src_cols);
    fast_accel_AXILiteS_s_axi_U->threshold(threshold);
    fast_accel_AXILiteS_s_axi_U->unused(unused);
    Block_Mat_exit73_pro_U0 = new Block_Mat_exit73_pro("Block_Mat_exit73_pro_U0");
    Block_Mat_exit73_pro_U0->ap_clk(ap_clk);
    Block_Mat_exit73_pro_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit73_pro_U0->ap_start(Block_Mat_exit73_pro_U0_ap_start);
    Block_Mat_exit73_pro_U0->start_full_n(start_for_fast_U0_full_n);
    Block_Mat_exit73_pro_U0->ap_done(Block_Mat_exit73_pro_U0_ap_done);
    Block_Mat_exit73_pro_U0->ap_continue(Block_Mat_exit73_pro_U0_ap_continue);
    Block_Mat_exit73_pro_U0->ap_idle(Block_Mat_exit73_pro_U0_ap_idle);
    Block_Mat_exit73_pro_U0->ap_ready(Block_Mat_exit73_pro_U0_ap_ready);
    Block_Mat_exit73_pro_U0->start_out(Block_Mat_exit73_pro_U0_start_out);
    Block_Mat_exit73_pro_U0->start_write(Block_Mat_exit73_pro_U0_start_write);
    Block_Mat_exit73_pro_U0->src_rows(src_rows);
    Block_Mat_exit73_pro_U0->src_cols(src_cols);
    Block_Mat_exit73_pro_U0->threshold(threshold);
    Block_Mat_exit73_pro_U0->src_mat_rows_out_din(Block_Mat_exit73_pro_U0_src_mat_rows_out_din);
    Block_Mat_exit73_pro_U0->src_mat_rows_out_full_n(src_mat_rows_c_full_n);
    Block_Mat_exit73_pro_U0->src_mat_rows_out_write(Block_Mat_exit73_pro_U0_src_mat_rows_out_write);
    Block_Mat_exit73_pro_U0->src_mat_cols_out_din(Block_Mat_exit73_pro_U0_src_mat_cols_out_din);
    Block_Mat_exit73_pro_U0->src_mat_cols_out_full_n(src_mat_cols_c_full_n);
    Block_Mat_exit73_pro_U0->src_mat_cols_out_write(Block_Mat_exit73_pro_U0_src_mat_cols_out_write);
    Block_Mat_exit73_pro_U0->src_rows_cast1_out_out_din(Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_din);
    Block_Mat_exit73_pro_U0->src_rows_cast1_out_out_full_n(src_rows_cast1_loc_c_full_n);
    Block_Mat_exit73_pro_U0->src_rows_cast1_out_out_write(Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_write);
    Block_Mat_exit73_pro_U0->src_cols_cast2_out_out_din(Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_din);
    Block_Mat_exit73_pro_U0->src_cols_cast2_out_out_full_n(src_cols_cast2_loc_c_full_n);
    Block_Mat_exit73_pro_U0->src_cols_cast2_out_out_write(Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_write);
    Block_Mat_exit73_pro_U0->threshold_out_din(Block_Mat_exit73_pro_U0_threshold_out_din);
    Block_Mat_exit73_pro_U0->threshold_out_full_n(threshold_c_full_n);
    Block_Mat_exit73_pro_U0->threshold_out_write(Block_Mat_exit73_pro_U0_threshold_out_write);
    axis2xfMat_U0 = new axis2xfMat("axis2xfMat_U0");
    axis2xfMat_U0->ap_clk(ap_clk);
    axis2xfMat_U0->ap_rst(ap_rst_n_inv);
    axis2xfMat_U0->ap_start(axis2xfMat_U0_ap_start);
    axis2xfMat_U0->start_full_n(start_for_xfMat2axis_U0_full_n);
    axis2xfMat_U0->ap_done(axis2xfMat_U0_ap_done);
    axis2xfMat_U0->ap_continue(axis2xfMat_U0_ap_continue);
    axis2xfMat_U0->ap_idle(axis2xfMat_U0_ap_idle);
    axis2xfMat_U0->ap_ready(axis2xfMat_U0_ap_ready);
    axis2xfMat_U0->start_out(axis2xfMat_U0_start_out);
    axis2xfMat_U0->start_write(axis2xfMat_U0_start_write);
    axis2xfMat_U0->src_TDATA(src_TDATA);
    axis2xfMat_U0->src_TVALID(src_TVALID);
    axis2xfMat_U0->src_TREADY(axis2xfMat_U0_src_TREADY);
    axis2xfMat_U0->p_src_data_V_din(axis2xfMat_U0_p_src_data_V_din);
    axis2xfMat_U0->p_src_data_V_full_n(src_mat_data_V_full_n);
    axis2xfMat_U0->p_src_data_V_write(axis2xfMat_U0_p_src_data_V_write);
    axis2xfMat_U0->src_rows_cast1_loc_dout(src_rows_cast1_loc_c_dout);
    axis2xfMat_U0->src_rows_cast1_loc_empty_n(src_rows_cast1_loc_c_empty_n);
    axis2xfMat_U0->src_rows_cast1_loc_read(axis2xfMat_U0_src_rows_cast1_loc_read);
    axis2xfMat_U0->src_cols_cast2_loc_dout(src_cols_cast2_loc_c_dout);
    axis2xfMat_U0->src_cols_cast2_loc_empty_n(src_cols_cast2_loc_c_empty_n);
    axis2xfMat_U0->src_cols_cast2_loc_read(axis2xfMat_U0_src_cols_cast2_loc_read);
    axis2xfMat_U0->src_rows_cast1_loc_out_din(axis2xfMat_U0_src_rows_cast1_loc_out_din);
    axis2xfMat_U0->src_rows_cast1_loc_out_full_n(src_rows_cast1_loc_c_1_full_n);
    axis2xfMat_U0->src_rows_cast1_loc_out_write(axis2xfMat_U0_src_rows_cast1_loc_out_write);
    axis2xfMat_U0->src_cols_cast2_loc_out_din(axis2xfMat_U0_src_cols_cast2_loc_out_din);
    axis2xfMat_U0->src_cols_cast2_loc_out_full_n(src_cols_cast2_loc_c_1_full_n);
    axis2xfMat_U0->src_cols_cast2_loc_out_write(axis2xfMat_U0_src_cols_cast2_loc_out_write);
    fast_U0 = new fast("fast_U0");
    fast_U0->ap_clk(ap_clk);
    fast_U0->ap_rst(ap_rst_n_inv);
    fast_U0->ap_start(fast_U0_ap_start);
    fast_U0->ap_done(fast_U0_ap_done);
    fast_U0->ap_continue(fast_U0_ap_continue);
    fast_U0->ap_idle(fast_U0_ap_idle);
    fast_U0->ap_ready(fast_U0_ap_ready);
    fast_U0->p_src_mat_rows_dout(src_mat_rows_c_dout);
    fast_U0->p_src_mat_rows_empty_n(src_mat_rows_c_empty_n);
    fast_U0->p_src_mat_rows_read(fast_U0_p_src_mat_rows_read);
    fast_U0->p_src_mat_cols_dout(src_mat_cols_c_dout);
    fast_U0->p_src_mat_cols_empty_n(src_mat_cols_c_empty_n);
    fast_U0->p_src_mat_cols_read(fast_U0_p_src_mat_cols_read);
    fast_U0->p_src_mat_data_V_dout(src_mat_data_V_dout);
    fast_U0->p_src_mat_data_V_empty_n(src_mat_data_V_empty_n);
    fast_U0->p_src_mat_data_V_read(fast_U0_p_src_mat_data_V_read);
    fast_U0->p_dst_mat_data_V_din(fast_U0_p_dst_mat_data_V_din);
    fast_U0->p_dst_mat_data_V_full_n(dst_mat_data_V_full_n);
    fast_U0->p_dst_mat_data_V_write(fast_U0_p_dst_mat_data_V_write);
    fast_U0->threshold_dout(threshold_c_dout);
    fast_U0->threshold_empty_n(threshold_c_empty_n);
    fast_U0->threshold_read(fast_U0_threshold_read);
    xfMat2axis_U0 = new xfMat2axis("xfMat2axis_U0");
    xfMat2axis_U0->ap_clk(ap_clk);
    xfMat2axis_U0->ap_rst(ap_rst_n_inv);
    xfMat2axis_U0->ap_start(xfMat2axis_U0_ap_start);
    xfMat2axis_U0->ap_done(xfMat2axis_U0_ap_done);
    xfMat2axis_U0->ap_continue(xfMat2axis_U0_ap_continue);
    xfMat2axis_U0->ap_idle(xfMat2axis_U0_ap_idle);
    xfMat2axis_U0->ap_ready(xfMat2axis_U0_ap_ready);
    xfMat2axis_U0->p_dst_data_V_dout(dst_mat_data_V_dout);
    xfMat2axis_U0->p_dst_data_V_empty_n(dst_mat_data_V_empty_n);
    xfMat2axis_U0->p_dst_data_V_read(xfMat2axis_U0_p_dst_data_V_read);
    xfMat2axis_U0->dst_TDATA(xfMat2axis_U0_dst_TDATA);
    xfMat2axis_U0->dst_TVALID(xfMat2axis_U0_dst_TVALID);
    xfMat2axis_U0->dst_TREADY(dst_TREADY);
    xfMat2axis_U0->dst_TLAST(xfMat2axis_U0_dst_TLAST);
    xfMat2axis_U0->src_rows_cast1_loc_dout(src_rows_cast1_loc_c_1_dout);
    xfMat2axis_U0->src_rows_cast1_loc_empty_n(src_rows_cast1_loc_c_1_empty_n);
    xfMat2axis_U0->src_rows_cast1_loc_read(xfMat2axis_U0_src_rows_cast1_loc_read);
    xfMat2axis_U0->src_cols_cast2_loc_dout(src_cols_cast2_loc_c_1_dout);
    xfMat2axis_U0->src_cols_cast2_loc_empty_n(src_cols_cast2_loc_c_1_empty_n);
    xfMat2axis_U0->src_cols_cast2_loc_read(xfMat2axis_U0_src_cols_cast2_loc_read);
    src_mat_rows_c_U = new fifo_w32_d3_A("src_mat_rows_c_U");
    src_mat_rows_c_U->clk(ap_clk);
    src_mat_rows_c_U->reset(ap_rst_n_inv);
    src_mat_rows_c_U->if_read_ce(ap_var_for_const0);
    src_mat_rows_c_U->if_write_ce(ap_var_for_const0);
    src_mat_rows_c_U->if_din(Block_Mat_exit73_pro_U0_src_mat_rows_out_din);
    src_mat_rows_c_U->if_full_n(src_mat_rows_c_full_n);
    src_mat_rows_c_U->if_write(Block_Mat_exit73_pro_U0_src_mat_rows_out_write);
    src_mat_rows_c_U->if_dout(src_mat_rows_c_dout);
    src_mat_rows_c_U->if_empty_n(src_mat_rows_c_empty_n);
    src_mat_rows_c_U->if_read(fast_U0_p_src_mat_rows_read);
    src_mat_cols_c_U = new fifo_w32_d3_A("src_mat_cols_c_U");
    src_mat_cols_c_U->clk(ap_clk);
    src_mat_cols_c_U->reset(ap_rst_n_inv);
    src_mat_cols_c_U->if_read_ce(ap_var_for_const0);
    src_mat_cols_c_U->if_write_ce(ap_var_for_const0);
    src_mat_cols_c_U->if_din(Block_Mat_exit73_pro_U0_src_mat_cols_out_din);
    src_mat_cols_c_U->if_full_n(src_mat_cols_c_full_n);
    src_mat_cols_c_U->if_write(Block_Mat_exit73_pro_U0_src_mat_cols_out_write);
    src_mat_cols_c_U->if_dout(src_mat_cols_c_dout);
    src_mat_cols_c_U->if_empty_n(src_mat_cols_c_empty_n);
    src_mat_cols_c_U->if_read(fast_U0_p_src_mat_cols_read);
    src_rows_cast1_loc_c_U = new fifo_w12_d2_A_x("src_rows_cast1_loc_c_U");
    src_rows_cast1_loc_c_U->clk(ap_clk);
    src_rows_cast1_loc_c_U->reset(ap_rst_n_inv);
    src_rows_cast1_loc_c_U->if_read_ce(ap_var_for_const0);
    src_rows_cast1_loc_c_U->if_write_ce(ap_var_for_const0);
    src_rows_cast1_loc_c_U->if_din(Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_din);
    src_rows_cast1_loc_c_U->if_full_n(src_rows_cast1_loc_c_full_n);
    src_rows_cast1_loc_c_U->if_write(Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_write);
    src_rows_cast1_loc_c_U->if_dout(src_rows_cast1_loc_c_dout);
    src_rows_cast1_loc_c_U->if_empty_n(src_rows_cast1_loc_c_empty_n);
    src_rows_cast1_loc_c_U->if_read(axis2xfMat_U0_src_rows_cast1_loc_read);
    src_cols_cast2_loc_c_U = new fifo_w12_d2_A_x("src_cols_cast2_loc_c_U");
    src_cols_cast2_loc_c_U->clk(ap_clk);
    src_cols_cast2_loc_c_U->reset(ap_rst_n_inv);
    src_cols_cast2_loc_c_U->if_read_ce(ap_var_for_const0);
    src_cols_cast2_loc_c_U->if_write_ce(ap_var_for_const0);
    src_cols_cast2_loc_c_U->if_din(Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_din);
    src_cols_cast2_loc_c_U->if_full_n(src_cols_cast2_loc_c_full_n);
    src_cols_cast2_loc_c_U->if_write(Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_write);
    src_cols_cast2_loc_c_U->if_dout(src_cols_cast2_loc_c_dout);
    src_cols_cast2_loc_c_U->if_empty_n(src_cols_cast2_loc_c_empty_n);
    src_cols_cast2_loc_c_U->if_read(axis2xfMat_U0_src_cols_cast2_loc_read);
    threshold_c_U = new fifo_w32_d3_A("threshold_c_U");
    threshold_c_U->clk(ap_clk);
    threshold_c_U->reset(ap_rst_n_inv);
    threshold_c_U->if_read_ce(ap_var_for_const0);
    threshold_c_U->if_write_ce(ap_var_for_const0);
    threshold_c_U->if_din(Block_Mat_exit73_pro_U0_threshold_out_din);
    threshold_c_U->if_full_n(threshold_c_full_n);
    threshold_c_U->if_write(Block_Mat_exit73_pro_U0_threshold_out_write);
    threshold_c_U->if_dout(threshold_c_dout);
    threshold_c_U->if_empty_n(threshold_c_empty_n);
    threshold_c_U->if_read(fast_U0_threshold_read);
    src_mat_data_V_U = new fifo_w8_d150_A("src_mat_data_V_U");
    src_mat_data_V_U->clk(ap_clk);
    src_mat_data_V_U->reset(ap_rst_n_inv);
    src_mat_data_V_U->if_read_ce(ap_var_for_const0);
    src_mat_data_V_U->if_write_ce(ap_var_for_const0);
    src_mat_data_V_U->if_din(axis2xfMat_U0_p_src_data_V_din);
    src_mat_data_V_U->if_full_n(src_mat_data_V_full_n);
    src_mat_data_V_U->if_write(axis2xfMat_U0_p_src_data_V_write);
    src_mat_data_V_U->if_dout(src_mat_data_V_dout);
    src_mat_data_V_U->if_empty_n(src_mat_data_V_empty_n);
    src_mat_data_V_U->if_read(fast_U0_p_src_mat_data_V_read);
    src_rows_cast1_loc_c_1_U = new fifo_w12_d3_A("src_rows_cast1_loc_c_1_U");
    src_rows_cast1_loc_c_1_U->clk(ap_clk);
    src_rows_cast1_loc_c_1_U->reset(ap_rst_n_inv);
    src_rows_cast1_loc_c_1_U->if_read_ce(ap_var_for_const0);
    src_rows_cast1_loc_c_1_U->if_write_ce(ap_var_for_const0);
    src_rows_cast1_loc_c_1_U->if_din(axis2xfMat_U0_src_rows_cast1_loc_out_din);
    src_rows_cast1_loc_c_1_U->if_full_n(src_rows_cast1_loc_c_1_full_n);
    src_rows_cast1_loc_c_1_U->if_write(axis2xfMat_U0_src_rows_cast1_loc_out_write);
    src_rows_cast1_loc_c_1_U->if_dout(src_rows_cast1_loc_c_1_dout);
    src_rows_cast1_loc_c_1_U->if_empty_n(src_rows_cast1_loc_c_1_empty_n);
    src_rows_cast1_loc_c_1_U->if_read(xfMat2axis_U0_src_rows_cast1_loc_read);
    src_cols_cast2_loc_c_1_U = new fifo_w12_d3_A("src_cols_cast2_loc_c_1_U");
    src_cols_cast2_loc_c_1_U->clk(ap_clk);
    src_cols_cast2_loc_c_1_U->reset(ap_rst_n_inv);
    src_cols_cast2_loc_c_1_U->if_read_ce(ap_var_for_const0);
    src_cols_cast2_loc_c_1_U->if_write_ce(ap_var_for_const0);
    src_cols_cast2_loc_c_1_U->if_din(axis2xfMat_U0_src_cols_cast2_loc_out_din);
    src_cols_cast2_loc_c_1_U->if_full_n(src_cols_cast2_loc_c_1_full_n);
    src_cols_cast2_loc_c_1_U->if_write(axis2xfMat_U0_src_cols_cast2_loc_out_write);
    src_cols_cast2_loc_c_1_U->if_dout(src_cols_cast2_loc_c_1_dout);
    src_cols_cast2_loc_c_1_U->if_empty_n(src_cols_cast2_loc_c_1_empty_n);
    src_cols_cast2_loc_c_1_U->if_read(xfMat2axis_U0_src_cols_cast2_loc_read);
    dst_mat_data_V_U = new fifo_w1_d150_A("dst_mat_data_V_U");
    dst_mat_data_V_U->clk(ap_clk);
    dst_mat_data_V_U->reset(ap_rst_n_inv);
    dst_mat_data_V_U->if_read_ce(ap_var_for_const0);
    dst_mat_data_V_U->if_write_ce(ap_var_for_const0);
    dst_mat_data_V_U->if_din(fast_U0_p_dst_mat_data_V_din);
    dst_mat_data_V_U->if_full_n(dst_mat_data_V_full_n);
    dst_mat_data_V_U->if_write(fast_U0_p_dst_mat_data_V_write);
    dst_mat_data_V_U->if_dout(dst_mat_data_V_dout);
    dst_mat_data_V_U->if_empty_n(dst_mat_data_V_empty_n);
    dst_mat_data_V_U->if_read(xfMat2axis_U0_p_dst_data_V_read);
    start_for_fast_U0_U = new start_for_fast_U0("start_for_fast_U0_U");
    start_for_fast_U0_U->clk(ap_clk);
    start_for_fast_U0_U->reset(ap_rst_n_inv);
    start_for_fast_U0_U->if_read_ce(ap_var_for_const0);
    start_for_fast_U0_U->if_write_ce(ap_var_for_const0);
    start_for_fast_U0_U->if_din(start_for_fast_U0_din);
    start_for_fast_U0_U->if_full_n(start_for_fast_U0_full_n);
    start_for_fast_U0_U->if_write(Block_Mat_exit73_pro_U0_start_write);
    start_for_fast_U0_U->if_dout(start_for_fast_U0_dout);
    start_for_fast_U0_U->if_empty_n(start_for_fast_U0_empty_n);
    start_for_fast_U0_U->if_read(fast_U0_ap_ready);
    start_for_xfMat2aqcK_U = new start_for_xfMat2aqcK("start_for_xfMat2aqcK_U");
    start_for_xfMat2aqcK_U->clk(ap_clk);
    start_for_xfMat2aqcK_U->reset(ap_rst_n_inv);
    start_for_xfMat2aqcK_U->if_read_ce(ap_var_for_const0);
    start_for_xfMat2aqcK_U->if_write_ce(ap_var_for_const0);
    start_for_xfMat2aqcK_U->if_din(start_for_xfMat2axis_U0_din);
    start_for_xfMat2aqcK_U->if_full_n(start_for_xfMat2axis_U0_full_n);
    start_for_xfMat2aqcK_U->if_write(axis2xfMat_U0_start_write);
    start_for_xfMat2aqcK_U->if_dout(start_for_xfMat2axis_U0_dout);
    start_for_xfMat2aqcK_U->if_empty_n(start_for_xfMat2axis_U0_empty_n);
    start_for_xfMat2aqcK_U->if_read(xfMat2axis_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Block_Mat_exit73_pro_U0_ap_continue);

    SC_METHOD(thread_Block_Mat_exit73_pro_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready );

    SC_METHOD(thread_ap_done);
    sensitive << ( xfMat2axis_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_Mat_exit73_pro_U0_ap_idle );
    sensitive << ( axis2xfMat_U0_ap_idle );
    sensitive << ( fast_U0_ap_idle );
    sensitive << ( xfMat2axis_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_Block_Mat_exit73_pro_U0_ap_ready);
    sensitive << ( Block_Mat_exit73_pro_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready );

    SC_METHOD(thread_ap_sync_axis2xfMat_U0_ap_ready);
    sensitive << ( axis2xfMat_U0_ap_ready );
    sensitive << ( ap_sync_reg_axis2xfMat_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( xfMat2axis_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_Block_Mat_exit73_pro_U0_ap_ready );
    sensitive << ( ap_sync_axis2xfMat_U0_ap_ready );

    SC_METHOD(thread_axis2xfMat_U0_ap_continue);

    SC_METHOD(thread_axis2xfMat_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_axis2xfMat_U0_ap_ready );

    SC_METHOD(thread_dst_TDATA);
    sensitive << ( xfMat2axis_U0_dst_TDATA );

    SC_METHOD(thread_dst_TLAST);
    sensitive << ( xfMat2axis_U0_dst_TLAST );

    SC_METHOD(thread_dst_TVALID);
    sensitive << ( xfMat2axis_U0_dst_TVALID );

    SC_METHOD(thread_fast_U0_ap_continue);

    SC_METHOD(thread_fast_U0_ap_start);
    sensitive << ( start_for_fast_U0_empty_n );

    SC_METHOD(thread_fast_U0_start_full_n);

    SC_METHOD(thread_fast_U0_start_write);

    SC_METHOD(thread_src_TREADY);
    sensitive << ( axis2xfMat_U0_src_TREADY );

    SC_METHOD(thread_start_for_fast_U0_din);

    SC_METHOD(thread_start_for_xfMat2axis_U0_din);

    SC_METHOD(thread_xfMat2axis_U0_ap_continue);

    SC_METHOD(thread_xfMat2axis_U0_ap_start);
    sensitive << ( start_for_xfMat2axis_U0_empty_n );

    SC_METHOD(thread_xfMat2axis_U0_start_full_n);

    SC_METHOD(thread_xfMat2axis_U0_start_write);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready = SC_LOGIC_0;
    Block_Mat_exit73_pro_U0_ap_ready_count = "00";
    ap_sync_reg_axis2xfMat_U0_ap_ready = SC_LOGIC_0;
    axis2xfMat_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fast_accel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, src_TDATA, "(port)src_TDATA");
    sc_trace(mVcdFile, src_TLAST, "(port)src_TLAST");
    sc_trace(mVcdFile, dst_TDATA, "(port)dst_TDATA");
    sc_trace(mVcdFile, dst_TLAST, "(port)dst_TLAST");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, src_TVALID, "(port)src_TVALID");
    sc_trace(mVcdFile, src_TREADY, "(port)src_TREADY");
    sc_trace(mVcdFile, dst_TVALID, "(port)dst_TVALID");
    sc_trace(mVcdFile, dst_TREADY, "(port)dst_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, src_rows, "src_rows");
    sc_trace(mVcdFile, src_cols, "src_cols");
    sc_trace(mVcdFile, threshold, "threshold");
    sc_trace(mVcdFile, unused, "unused");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_ap_start, "Block_Mat_exit73_pro_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_ap_done, "Block_Mat_exit73_pro_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_ap_continue, "Block_Mat_exit73_pro_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_ap_idle, "Block_Mat_exit73_pro_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_ap_ready, "Block_Mat_exit73_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_start_out, "Block_Mat_exit73_pro_U0_start_out");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_start_write, "Block_Mat_exit73_pro_U0_start_write");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_src_mat_rows_out_din, "Block_Mat_exit73_pro_U0_src_mat_rows_out_din");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_src_mat_rows_out_write, "Block_Mat_exit73_pro_U0_src_mat_rows_out_write");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_src_mat_cols_out_din, "Block_Mat_exit73_pro_U0_src_mat_cols_out_din");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_src_mat_cols_out_write, "Block_Mat_exit73_pro_U0_src_mat_cols_out_write");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_din, "Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_din");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_write, "Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_write");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_din, "Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_din");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_write, "Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_write");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_threshold_out_din, "Block_Mat_exit73_pro_U0_threshold_out_din");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_threshold_out_write, "Block_Mat_exit73_pro_U0_threshold_out_write");
    sc_trace(mVcdFile, axis2xfMat_U0_ap_start, "axis2xfMat_U0_ap_start");
    sc_trace(mVcdFile, axis2xfMat_U0_ap_done, "axis2xfMat_U0_ap_done");
    sc_trace(mVcdFile, axis2xfMat_U0_ap_continue, "axis2xfMat_U0_ap_continue");
    sc_trace(mVcdFile, axis2xfMat_U0_ap_idle, "axis2xfMat_U0_ap_idle");
    sc_trace(mVcdFile, axis2xfMat_U0_ap_ready, "axis2xfMat_U0_ap_ready");
    sc_trace(mVcdFile, axis2xfMat_U0_start_out, "axis2xfMat_U0_start_out");
    sc_trace(mVcdFile, axis2xfMat_U0_start_write, "axis2xfMat_U0_start_write");
    sc_trace(mVcdFile, axis2xfMat_U0_src_TREADY, "axis2xfMat_U0_src_TREADY");
    sc_trace(mVcdFile, axis2xfMat_U0_p_src_data_V_din, "axis2xfMat_U0_p_src_data_V_din");
    sc_trace(mVcdFile, axis2xfMat_U0_p_src_data_V_write, "axis2xfMat_U0_p_src_data_V_write");
    sc_trace(mVcdFile, axis2xfMat_U0_src_rows_cast1_loc_read, "axis2xfMat_U0_src_rows_cast1_loc_read");
    sc_trace(mVcdFile, axis2xfMat_U0_src_cols_cast2_loc_read, "axis2xfMat_U0_src_cols_cast2_loc_read");
    sc_trace(mVcdFile, axis2xfMat_U0_src_rows_cast1_loc_out_din, "axis2xfMat_U0_src_rows_cast1_loc_out_din");
    sc_trace(mVcdFile, axis2xfMat_U0_src_rows_cast1_loc_out_write, "axis2xfMat_U0_src_rows_cast1_loc_out_write");
    sc_trace(mVcdFile, axis2xfMat_U0_src_cols_cast2_loc_out_din, "axis2xfMat_U0_src_cols_cast2_loc_out_din");
    sc_trace(mVcdFile, axis2xfMat_U0_src_cols_cast2_loc_out_write, "axis2xfMat_U0_src_cols_cast2_loc_out_write");
    sc_trace(mVcdFile, fast_U0_ap_start, "fast_U0_ap_start");
    sc_trace(mVcdFile, fast_U0_ap_done, "fast_U0_ap_done");
    sc_trace(mVcdFile, fast_U0_ap_continue, "fast_U0_ap_continue");
    sc_trace(mVcdFile, fast_U0_ap_idle, "fast_U0_ap_idle");
    sc_trace(mVcdFile, fast_U0_ap_ready, "fast_U0_ap_ready");
    sc_trace(mVcdFile, fast_U0_p_src_mat_rows_read, "fast_U0_p_src_mat_rows_read");
    sc_trace(mVcdFile, fast_U0_p_src_mat_cols_read, "fast_U0_p_src_mat_cols_read");
    sc_trace(mVcdFile, fast_U0_p_src_mat_data_V_read, "fast_U0_p_src_mat_data_V_read");
    sc_trace(mVcdFile, fast_U0_p_dst_mat_data_V_din, "fast_U0_p_dst_mat_data_V_din");
    sc_trace(mVcdFile, fast_U0_p_dst_mat_data_V_write, "fast_U0_p_dst_mat_data_V_write");
    sc_trace(mVcdFile, fast_U0_threshold_read, "fast_U0_threshold_read");
    sc_trace(mVcdFile, xfMat2axis_U0_ap_start, "xfMat2axis_U0_ap_start");
    sc_trace(mVcdFile, xfMat2axis_U0_ap_done, "xfMat2axis_U0_ap_done");
    sc_trace(mVcdFile, xfMat2axis_U0_ap_continue, "xfMat2axis_U0_ap_continue");
    sc_trace(mVcdFile, xfMat2axis_U0_ap_idle, "xfMat2axis_U0_ap_idle");
    sc_trace(mVcdFile, xfMat2axis_U0_ap_ready, "xfMat2axis_U0_ap_ready");
    sc_trace(mVcdFile, xfMat2axis_U0_p_dst_data_V_read, "xfMat2axis_U0_p_dst_data_V_read");
    sc_trace(mVcdFile, xfMat2axis_U0_dst_TDATA, "xfMat2axis_U0_dst_TDATA");
    sc_trace(mVcdFile, xfMat2axis_U0_dst_TVALID, "xfMat2axis_U0_dst_TVALID");
    sc_trace(mVcdFile, xfMat2axis_U0_dst_TLAST, "xfMat2axis_U0_dst_TLAST");
    sc_trace(mVcdFile, xfMat2axis_U0_src_rows_cast1_loc_read, "xfMat2axis_U0_src_rows_cast1_loc_read");
    sc_trace(mVcdFile, xfMat2axis_U0_src_cols_cast2_loc_read, "xfMat2axis_U0_src_cols_cast2_loc_read");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, src_mat_rows_c_full_n, "src_mat_rows_c_full_n");
    sc_trace(mVcdFile, src_mat_rows_c_dout, "src_mat_rows_c_dout");
    sc_trace(mVcdFile, src_mat_rows_c_empty_n, "src_mat_rows_c_empty_n");
    sc_trace(mVcdFile, src_mat_cols_c_full_n, "src_mat_cols_c_full_n");
    sc_trace(mVcdFile, src_mat_cols_c_dout, "src_mat_cols_c_dout");
    sc_trace(mVcdFile, src_mat_cols_c_empty_n, "src_mat_cols_c_empty_n");
    sc_trace(mVcdFile, src_rows_cast1_loc_c_full_n, "src_rows_cast1_loc_c_full_n");
    sc_trace(mVcdFile, src_rows_cast1_loc_c_dout, "src_rows_cast1_loc_c_dout");
    sc_trace(mVcdFile, src_rows_cast1_loc_c_empty_n, "src_rows_cast1_loc_c_empty_n");
    sc_trace(mVcdFile, src_cols_cast2_loc_c_full_n, "src_cols_cast2_loc_c_full_n");
    sc_trace(mVcdFile, src_cols_cast2_loc_c_dout, "src_cols_cast2_loc_c_dout");
    sc_trace(mVcdFile, src_cols_cast2_loc_c_empty_n, "src_cols_cast2_loc_c_empty_n");
    sc_trace(mVcdFile, threshold_c_full_n, "threshold_c_full_n");
    sc_trace(mVcdFile, threshold_c_dout, "threshold_c_dout");
    sc_trace(mVcdFile, threshold_c_empty_n, "threshold_c_empty_n");
    sc_trace(mVcdFile, src_mat_data_V_full_n, "src_mat_data_V_full_n");
    sc_trace(mVcdFile, src_mat_data_V_dout, "src_mat_data_V_dout");
    sc_trace(mVcdFile, src_mat_data_V_empty_n, "src_mat_data_V_empty_n");
    sc_trace(mVcdFile, src_rows_cast1_loc_c_1_full_n, "src_rows_cast1_loc_c_1_full_n");
    sc_trace(mVcdFile, src_rows_cast1_loc_c_1_dout, "src_rows_cast1_loc_c_1_dout");
    sc_trace(mVcdFile, src_rows_cast1_loc_c_1_empty_n, "src_rows_cast1_loc_c_1_empty_n");
    sc_trace(mVcdFile, src_cols_cast2_loc_c_1_full_n, "src_cols_cast2_loc_c_1_full_n");
    sc_trace(mVcdFile, src_cols_cast2_loc_c_1_dout, "src_cols_cast2_loc_c_1_dout");
    sc_trace(mVcdFile, src_cols_cast2_loc_c_1_empty_n, "src_cols_cast2_loc_c_1_empty_n");
    sc_trace(mVcdFile, dst_mat_data_V_full_n, "dst_mat_data_V_full_n");
    sc_trace(mVcdFile, dst_mat_data_V_dout, "dst_mat_data_V_dout");
    sc_trace(mVcdFile, dst_mat_data_V_empty_n, "dst_mat_data_V_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready, "ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_Mat_exit73_pro_U0_ap_ready, "ap_sync_Block_Mat_exit73_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit73_pro_U0_ap_ready_count, "Block_Mat_exit73_pro_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_axis2xfMat_U0_ap_ready, "ap_sync_reg_axis2xfMat_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_axis2xfMat_U0_ap_ready, "ap_sync_axis2xfMat_U0_ap_ready");
    sc_trace(mVcdFile, axis2xfMat_U0_ap_ready_count, "axis2xfMat_U0_ap_ready_count");
    sc_trace(mVcdFile, start_for_fast_U0_din, "start_for_fast_U0_din");
    sc_trace(mVcdFile, start_for_fast_U0_full_n, "start_for_fast_U0_full_n");
    sc_trace(mVcdFile, start_for_fast_U0_dout, "start_for_fast_U0_dout");
    sc_trace(mVcdFile, start_for_fast_U0_empty_n, "start_for_fast_U0_empty_n");
    sc_trace(mVcdFile, start_for_xfMat2axis_U0_din, "start_for_xfMat2axis_U0_din");
    sc_trace(mVcdFile, start_for_xfMat2axis_U0_full_n, "start_for_xfMat2axis_U0_full_n");
    sc_trace(mVcdFile, start_for_xfMat2axis_U0_dout, "start_for_xfMat2axis_U0_dout");
    sc_trace(mVcdFile, start_for_xfMat2axis_U0_empty_n, "start_for_xfMat2axis_U0_empty_n");
    sc_trace(mVcdFile, fast_U0_start_full_n, "fast_U0_start_full_n");
    sc_trace(mVcdFile, fast_U0_start_write, "fast_U0_start_write");
    sc_trace(mVcdFile, xfMat2axis_U0_start_full_n, "xfMat2axis_U0_start_full_n");
    sc_trace(mVcdFile, xfMat2axis_U0_start_write, "xfMat2axis_U0_start_write");
#endif

    }
    mHdltvinHandle.open("fast_accel.hdltvin.dat");
    mHdltvoutHandle.open("fast_accel.hdltvout.dat");
}

fast_accel::~fast_accel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete fast_accel_AXILiteS_s_axi_U;
    delete Block_Mat_exit73_pro_U0;
    delete axis2xfMat_U0;
    delete fast_U0;
    delete xfMat2axis_U0;
    delete src_mat_rows_c_U;
    delete src_mat_cols_c_U;
    delete src_rows_cast1_loc_c_U;
    delete src_cols_cast2_loc_c_U;
    delete threshold_c_U;
    delete src_mat_data_V_U;
    delete src_rows_cast1_loc_c_1_U;
    delete src_cols_cast2_loc_c_1_U;
    delete dst_mat_data_V_U;
    delete start_for_fast_U0_U;
    delete start_for_xfMat2aqcK_U;
}

void fast_accel::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void fast_accel::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(Block_Mat_exit73_pro_U0_ap_ready.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        Block_Mat_exit73_pro_U0_ap_ready_count = (!Block_Mat_exit73_pro_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_Mat_exit73_pro_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, Block_Mat_exit73_pro_U0_ap_ready.read()) && 
                esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0))) {
        Block_Mat_exit73_pro_U0_ap_ready_count = (!Block_Mat_exit73_pro_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_Mat_exit73_pro_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready = ap_sync_Block_Mat_exit73_pro_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_axis2xfMat_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_axis2xfMat_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_axis2xfMat_U0_ap_ready = ap_sync_axis2xfMat_U0_ap_ready.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(axis2xfMat_U0_ap_ready.read(), ap_const_logic_0))) {
        axis2xfMat_U0_ap_ready_count = (!axis2xfMat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(axis2xfMat_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, axis2xfMat_U0_ap_ready.read()))) {
        axis2xfMat_U0_ap_ready_count = (!axis2xfMat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(axis2xfMat_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
}

void fast_accel::thread_Block_Mat_exit73_pro_U0_ap_continue() {
    Block_Mat_exit73_pro_U0_ap_continue = ap_const_logic_1;
}

void fast_accel::thread_Block_Mat_exit73_pro_U0_ap_start() {
    Block_Mat_exit73_pro_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void fast_accel::thread_ap_done() {
    ap_done = xfMat2axis_U0_ap_done.read();
}

void fast_accel::thread_ap_idle() {
    ap_idle = (Block_Mat_exit73_pro_U0_ap_idle.read() & axis2xfMat_U0_ap_idle.read() & fast_U0_ap_idle.read() & xfMat2axis_U0_ap_idle.read());
}

void fast_accel::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void fast_accel::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void fast_accel::thread_ap_sync_Block_Mat_exit73_pro_U0_ap_ready() {
    ap_sync_Block_Mat_exit73_pro_U0_ap_ready = (Block_Mat_exit73_pro_U0_ap_ready.read() | ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready.read());
}

void fast_accel::thread_ap_sync_axis2xfMat_U0_ap_ready() {
    ap_sync_axis2xfMat_U0_ap_ready = (axis2xfMat_U0_ap_ready.read() | ap_sync_reg_axis2xfMat_U0_ap_ready.read());
}

void fast_accel::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void fast_accel::thread_ap_sync_done() {
    ap_sync_done = xfMat2axis_U0_ap_done.read();
}

void fast_accel::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_Block_Mat_exit73_pro_U0_ap_ready.read() & ap_sync_axis2xfMat_U0_ap_ready.read());
}

void fast_accel::thread_axis2xfMat_U0_ap_continue() {
    axis2xfMat_U0_ap_continue = ap_const_logic_1;
}

void fast_accel::thread_axis2xfMat_U0_ap_start() {
    axis2xfMat_U0_ap_start = (ap_start.read() & (ap_sync_reg_axis2xfMat_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void fast_accel::thread_dst_TDATA() {
    dst_TDATA = xfMat2axis_U0_dst_TDATA.read();
}

void fast_accel::thread_dst_TLAST() {
    dst_TLAST = xfMat2axis_U0_dst_TLAST.read();
}

void fast_accel::thread_dst_TVALID() {
    dst_TVALID = xfMat2axis_U0_dst_TVALID.read();
}

void fast_accel::thread_fast_U0_ap_continue() {
    fast_U0_ap_continue = ap_const_logic_1;
}

void fast_accel::thread_fast_U0_ap_start() {
    fast_U0_ap_start = start_for_fast_U0_empty_n.read();
}

void fast_accel::thread_fast_U0_start_full_n() {
    fast_U0_start_full_n = ap_const_logic_1;
}

void fast_accel::thread_fast_U0_start_write() {
    fast_U0_start_write = ap_const_logic_0;
}

void fast_accel::thread_src_TREADY() {
    src_TREADY = axis2xfMat_U0_src_TREADY.read();
}

void fast_accel::thread_start_for_fast_U0_din() {
    start_for_fast_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void fast_accel::thread_start_for_xfMat2axis_U0_din() {
    start_for_xfMat2axis_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void fast_accel::thread_xfMat2axis_U0_ap_continue() {
    xfMat2axis_U0_ap_continue = ap_const_logic_1;
}

void fast_accel::thread_xfMat2axis_U0_ap_start() {
    xfMat2axis_U0_ap_start = start_for_xfMat2axis_U0_empty_n.read();
}

void fast_accel::thread_xfMat2axis_U0_start_full_n() {
    xfMat2axis_U0_start_full_n = ap_const_logic_1;
}

void fast_accel::thread_xfMat2axis_U0_start_write() {
    xfMat2axis_U0_start_write = ap_const_logic_0;
}

void fast_accel::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TDATA\" :  \"" << src_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TLAST\" :  \"" << src_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TDATA\" :  \"" << dst_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TLAST\" :  \"" << dst_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TVALID\" :  \"" << src_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"src_TREADY\" :  \"" << src_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TVALID\" :  \"" << dst_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dst_TREADY\" :  \"" << dst_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

