// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _fast_accel_HH_
#define _fast_accel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Block_Mat_exit73_pro.h"
#include "axis2xfMat.h"
#include "fast.h"
#include "xfMat2axis.h"
#include "fifo_w32_d3_A.h"
#include "fifo_w12_d2_A_x.h"
#include "fifo_w8_d150_A.h"
#include "fifo_w12_d3_A.h"
#include "fifo_w1_d150_A.h"
#include "start_for_fast_U0.h"
#include "start_for_xfMat2aqcK.h"
#include "fast_accel_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct fast_accel : public sc_module {
    // Port declarations 31
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<24> > src_TDATA;
    sc_in< sc_lv<1> > src_TLAST;
    sc_out< sc_lv<24> > dst_TDATA;
    sc_out< sc_lv<1> > dst_TLAST;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > src_TVALID;
    sc_out< sc_logic > src_TREADY;
    sc_out< sc_logic > dst_TVALID;
    sc_in< sc_logic > dst_TREADY;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    fast_accel(sc_module_name name);
    SC_HAS_PROCESS(fast_accel);

    ~fast_accel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    fast_accel_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* fast_accel_AXILiteS_s_axi_U;
    Block_Mat_exit73_pro* Block_Mat_exit73_pro_U0;
    axis2xfMat* axis2xfMat_U0;
    fast* fast_U0;
    xfMat2axis* xfMat2axis_U0;
    fifo_w32_d3_A* src_mat_rows_c_U;
    fifo_w32_d3_A* src_mat_cols_c_U;
    fifo_w12_d2_A_x* src_rows_cast1_loc_c_U;
    fifo_w12_d2_A_x* src_cols_cast2_loc_c_U;
    fifo_w32_d3_A* threshold_c_U;
    fifo_w8_d150_A* src_mat_data_V_U;
    fifo_w12_d3_A* src_rows_cast1_loc_c_1_U;
    fifo_w12_d3_A* src_cols_cast2_loc_c_1_U;
    fifo_w1_d150_A* dst_mat_data_V_U;
    start_for_fast_U0* start_for_fast_U0_U;
    start_for_xfMat2aqcK* start_for_xfMat2aqcK_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > src_rows;
    sc_signal< sc_lv<32> > src_cols;
    sc_signal< sc_lv<32> > threshold;
    sc_signal< sc_lv<32> > unused;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_ap_start;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_ap_done;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_ap_continue;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_ap_idle;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_ap_ready;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_start_out;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_start_write;
    sc_signal< sc_lv<32> > Block_Mat_exit73_pro_U0_src_mat_rows_out_din;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_src_mat_rows_out_write;
    sc_signal< sc_lv<32> > Block_Mat_exit73_pro_U0_src_mat_cols_out_din;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_src_mat_cols_out_write;
    sc_signal< sc_lv<12> > Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_din;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_src_rows_cast1_out_out_write;
    sc_signal< sc_lv<12> > Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_din;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_src_cols_cast2_out_out_write;
    sc_signal< sc_lv<32> > Block_Mat_exit73_pro_U0_threshold_out_din;
    sc_signal< sc_logic > Block_Mat_exit73_pro_U0_threshold_out_write;
    sc_signal< sc_logic > axis2xfMat_U0_ap_start;
    sc_signal< sc_logic > axis2xfMat_U0_ap_done;
    sc_signal< sc_logic > axis2xfMat_U0_ap_continue;
    sc_signal< sc_logic > axis2xfMat_U0_ap_idle;
    sc_signal< sc_logic > axis2xfMat_U0_ap_ready;
    sc_signal< sc_logic > axis2xfMat_U0_start_out;
    sc_signal< sc_logic > axis2xfMat_U0_start_write;
    sc_signal< sc_logic > axis2xfMat_U0_src_TREADY;
    sc_signal< sc_lv<8> > axis2xfMat_U0_p_src_data_V_din;
    sc_signal< sc_logic > axis2xfMat_U0_p_src_data_V_write;
    sc_signal< sc_logic > axis2xfMat_U0_src_rows_cast1_loc_read;
    sc_signal< sc_logic > axis2xfMat_U0_src_cols_cast2_loc_read;
    sc_signal< sc_lv<12> > axis2xfMat_U0_src_rows_cast1_loc_out_din;
    sc_signal< sc_logic > axis2xfMat_U0_src_rows_cast1_loc_out_write;
    sc_signal< sc_lv<12> > axis2xfMat_U0_src_cols_cast2_loc_out_din;
    sc_signal< sc_logic > axis2xfMat_U0_src_cols_cast2_loc_out_write;
    sc_signal< sc_logic > fast_U0_ap_start;
    sc_signal< sc_logic > fast_U0_ap_done;
    sc_signal< sc_logic > fast_U0_ap_continue;
    sc_signal< sc_logic > fast_U0_ap_idle;
    sc_signal< sc_logic > fast_U0_ap_ready;
    sc_signal< sc_logic > fast_U0_p_src_mat_rows_read;
    sc_signal< sc_logic > fast_U0_p_src_mat_cols_read;
    sc_signal< sc_logic > fast_U0_p_src_mat_data_V_read;
    sc_signal< sc_lv<1> > fast_U0_p_dst_mat_data_V_din;
    sc_signal< sc_logic > fast_U0_p_dst_mat_data_V_write;
    sc_signal< sc_logic > fast_U0_threshold_read;
    sc_signal< sc_logic > xfMat2axis_U0_ap_start;
    sc_signal< sc_logic > xfMat2axis_U0_ap_done;
    sc_signal< sc_logic > xfMat2axis_U0_ap_continue;
    sc_signal< sc_logic > xfMat2axis_U0_ap_idle;
    sc_signal< sc_logic > xfMat2axis_U0_ap_ready;
    sc_signal< sc_logic > xfMat2axis_U0_p_dst_data_V_read;
    sc_signal< sc_lv<24> > xfMat2axis_U0_dst_TDATA;
    sc_signal< sc_logic > xfMat2axis_U0_dst_TVALID;
    sc_signal< sc_lv<1> > xfMat2axis_U0_dst_TLAST;
    sc_signal< sc_logic > xfMat2axis_U0_src_rows_cast1_loc_read;
    sc_signal< sc_logic > xfMat2axis_U0_src_cols_cast2_loc_read;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > src_mat_rows_c_full_n;
    sc_signal< sc_lv<32> > src_mat_rows_c_dout;
    sc_signal< sc_logic > src_mat_rows_c_empty_n;
    sc_signal< sc_logic > src_mat_cols_c_full_n;
    sc_signal< sc_lv<32> > src_mat_cols_c_dout;
    sc_signal< sc_logic > src_mat_cols_c_empty_n;
    sc_signal< sc_logic > src_rows_cast1_loc_c_full_n;
    sc_signal< sc_lv<12> > src_rows_cast1_loc_c_dout;
    sc_signal< sc_logic > src_rows_cast1_loc_c_empty_n;
    sc_signal< sc_logic > src_cols_cast2_loc_c_full_n;
    sc_signal< sc_lv<12> > src_cols_cast2_loc_c_dout;
    sc_signal< sc_logic > src_cols_cast2_loc_c_empty_n;
    sc_signal< sc_logic > threshold_c_full_n;
    sc_signal< sc_lv<32> > threshold_c_dout;
    sc_signal< sc_logic > threshold_c_empty_n;
    sc_signal< sc_logic > src_mat_data_V_full_n;
    sc_signal< sc_lv<8> > src_mat_data_V_dout;
    sc_signal< sc_logic > src_mat_data_V_empty_n;
    sc_signal< sc_logic > src_rows_cast1_loc_c_1_full_n;
    sc_signal< sc_lv<12> > src_rows_cast1_loc_c_1_dout;
    sc_signal< sc_logic > src_rows_cast1_loc_c_1_empty_n;
    sc_signal< sc_logic > src_cols_cast2_loc_c_1_full_n;
    sc_signal< sc_lv<12> > src_cols_cast2_loc_c_1_dout;
    sc_signal< sc_logic > src_cols_cast2_loc_c_1_empty_n;
    sc_signal< sc_logic > dst_mat_data_V_full_n;
    sc_signal< sc_lv<1> > dst_mat_data_V_dout;
    sc_signal< sc_logic > dst_mat_data_V_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_Block_Mat_exit73_pro_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Block_Mat_exit73_pro_U0_ap_ready;
    sc_signal< sc_lv<2> > Block_Mat_exit73_pro_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_axis2xfMat_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_axis2xfMat_U0_ap_ready;
    sc_signal< sc_lv<2> > axis2xfMat_U0_ap_ready_count;
    sc_signal< sc_lv<1> > start_for_fast_U0_din;
    sc_signal< sc_logic > start_for_fast_U0_full_n;
    sc_signal< sc_lv<1> > start_for_fast_U0_dout;
    sc_signal< sc_logic > start_for_fast_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_xfMat2axis_U0_din;
    sc_signal< sc_logic > start_for_xfMat2axis_U0_full_n;
    sc_signal< sc_lv<1> > start_for_xfMat2axis_U0_dout;
    sc_signal< sc_logic > start_for_xfMat2axis_U0_empty_n;
    sc_signal< sc_logic > fast_U0_start_full_n;
    sc_signal< sc_logic > fast_U0_start_write;
    sc_signal< sc_logic > xfMat2axis_U0_start_full_n;
    sc_signal< sc_logic > xfMat2axis_U0_start_write;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_S_AXI_WSTRB_WIDTH;
    static const int C_S_AXI_ADDR_WIDTH;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_Block_Mat_exit73_pro_U0_ap_continue();
    void thread_Block_Mat_exit73_pro_U0_ap_start();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_Block_Mat_exit73_pro_U0_ap_ready();
    void thread_ap_sync_axis2xfMat_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_axis2xfMat_U0_ap_continue();
    void thread_axis2xfMat_U0_ap_start();
    void thread_dst_TDATA();
    void thread_dst_TLAST();
    void thread_dst_TVALID();
    void thread_fast_U0_ap_continue();
    void thread_fast_U0_ap_start();
    void thread_fast_U0_start_full_n();
    void thread_fast_U0_start_write();
    void thread_src_TREADY();
    void thread_start_for_fast_U0_din();
    void thread_start_for_xfMat2axis_U0_din();
    void thread_xfMat2axis_U0_ap_continue();
    void thread_xfMat2axis_U0_ap_start();
    void thread_xfMat2axis_U0_start_full_n();
    void thread_xfMat2axis_U0_start_write();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
