// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "xFFastCornerDetectio.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic xFFastCornerDetectio::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> xFFastCornerDetectio::ap_const_lv1_0 = "0";
const sc_logic xFFastCornerDetectio::ap_const_logic_1 = sc_dt::Log_1;

xFFastCornerDetectio::xFFastCornerDetectio(sc_module_name name) : sc_module(name), mVcdFile(0) {
    xFfast7x75682_U0 = new xFfast7x75682("xFfast7x75682_U0");
    xFfast7x75682_U0->ap_clk(ap_clk);
    xFfast7x75682_U0->ap_rst(ap_rst);
    xFfast7x75682_U0->ap_start(xFfast7x75682_U0_ap_start);
    xFfast7x75682_U0->start_full_n(start_for_xFfastnms5781_U0_full_n);
    xFfast7x75682_U0->ap_done(xFfast7x75682_U0_ap_done);
    xFfast7x75682_U0->ap_continue(xFfast7x75682_U0_ap_continue);
    xFfast7x75682_U0->ap_idle(xFfast7x75682_U0_ap_idle);
    xFfast7x75682_U0->ap_ready(xFfast7x75682_U0_ap_ready);
    xFfast7x75682_U0->start_out(xFfast7x75682_U0_start_out);
    xFfast7x75682_U0->start_write(xFfast7x75682_U0_start_write);
    xFfast7x75682_U0->p_src_mat_data_V_dout(p_src_mat_data_V_dout);
    xFfast7x75682_U0->p_src_mat_data_V_empty_n(p_src_mat_data_V_empty_n);
    xFfast7x75682_U0->p_src_mat_data_V_read(xFfast7x75682_U0_p_src_mat_data_V_read);
    xFfast7x75682_U0->p_dst_data_V_din(xFfast7x75682_U0_p_dst_data_V_din);
    xFfast7x75682_U0->p_dst_data_V_full_n(p_dst_data_V_full_n);
    xFfast7x75682_U0->p_dst_data_V_write(xFfast7x75682_U0_p_dst_data_V_write);
    xFfast7x75682_U0->p_image_height(p_image_height);
    xFfast7x75682_U0->p_image_width(p_image_width);
    xFfast7x75682_U0->p_threshold(p_threshold);
    xFfast7x75682_U0->p_image_height_c_din(xFfast7x75682_U0_p_image_height_c_din);
    xFfast7x75682_U0->p_image_height_c_full_n(p_image_height_c_full_n);
    xFfast7x75682_U0->p_image_height_c_write(xFfast7x75682_U0_p_image_height_c_write);
    xFfast7x75682_U0->p_image_width_c_din(xFfast7x75682_U0_p_image_width_c_din);
    xFfast7x75682_U0->p_image_width_c_full_n(p_image_width_c_full_n);
    xFfast7x75682_U0->p_image_width_c_write(xFfast7x75682_U0_p_image_width_c_write);
    xFfastnms5781_U0 = new xFfastnms5781("xFfastnms5781_U0");
    xFfastnms5781_U0->ap_clk(ap_clk);
    xFfastnms5781_U0->ap_rst(ap_rst);
    xFfastnms5781_U0->ap_start(xFfastnms5781_U0_ap_start);
    xFfastnms5781_U0->ap_done(xFfastnms5781_U0_ap_done);
    xFfastnms5781_U0->ap_continue(xFfastnms5781_U0_ap_continue);
    xFfastnms5781_U0->ap_idle(xFfastnms5781_U0_ap_idle);
    xFfastnms5781_U0->ap_ready(xFfastnms5781_U0_ap_ready);
    xFfastnms5781_U0->p_dst_data_V_dout(p_dst_data_V_dout);
    xFfastnms5781_U0->p_dst_data_V_empty_n(p_dst_data_V_empty_n);
    xFfastnms5781_U0->p_dst_data_V_read(xFfastnms5781_U0_p_dst_data_V_read);
    xFfastnms5781_U0->p_dst_mat_data_V_din(xFfastnms5781_U0_p_dst_mat_data_V_din);
    xFfastnms5781_U0->p_dst_mat_data_V_full_n(p_dst_mat_data_V_full_n);
    xFfastnms5781_U0->p_dst_mat_data_V_write(xFfastnms5781_U0_p_dst_mat_data_V_write);
    xFfastnms5781_U0->p_image_height_dout(p_image_height_c_dout);
    xFfastnms5781_U0->p_image_height_empty_n(p_image_height_c_empty_n);
    xFfastnms5781_U0->p_image_height_read(xFfastnms5781_U0_p_image_height_read);
    xFfastnms5781_U0->p_image_width_dout(p_image_width_c_dout);
    xFfastnms5781_U0->p_image_width_empty_n(p_image_width_c_empty_n);
    xFfastnms5781_U0->p_image_width_read(xFfastnms5781_U0_p_image_width_read);
    p_dst_data_V_U = new fifo_w8_d2_A("p_dst_data_V_U");
    p_dst_data_V_U->clk(ap_clk);
    p_dst_data_V_U->reset(ap_rst);
    p_dst_data_V_U->if_read_ce(ap_var_for_const0);
    p_dst_data_V_U->if_write_ce(ap_var_for_const0);
    p_dst_data_V_U->if_din(xFfast7x75682_U0_p_dst_data_V_din);
    p_dst_data_V_U->if_full_n(p_dst_data_V_full_n);
    p_dst_data_V_U->if_write(xFfast7x75682_U0_p_dst_data_V_write);
    p_dst_data_V_U->if_dout(p_dst_data_V_dout);
    p_dst_data_V_U->if_empty_n(p_dst_data_V_empty_n);
    p_dst_data_V_U->if_read(xFfastnms5781_U0_p_dst_data_V_read);
    p_image_height_c_U = new fifo_w12_d2_A("p_image_height_c_U");
    p_image_height_c_U->clk(ap_clk);
    p_image_height_c_U->reset(ap_rst);
    p_image_height_c_U->if_read_ce(ap_var_for_const0);
    p_image_height_c_U->if_write_ce(ap_var_for_const0);
    p_image_height_c_U->if_din(xFfast7x75682_U0_p_image_height_c_din);
    p_image_height_c_U->if_full_n(p_image_height_c_full_n);
    p_image_height_c_U->if_write(xFfast7x75682_U0_p_image_height_c_write);
    p_image_height_c_U->if_dout(p_image_height_c_dout);
    p_image_height_c_U->if_empty_n(p_image_height_c_empty_n);
    p_image_height_c_U->if_read(xFfastnms5781_U0_p_image_height_read);
    p_image_width_c_U = new fifo_w12_d2_A("p_image_width_c_U");
    p_image_width_c_U->clk(ap_clk);
    p_image_width_c_U->reset(ap_rst);
    p_image_width_c_U->if_read_ce(ap_var_for_const0);
    p_image_width_c_U->if_write_ce(ap_var_for_const0);
    p_image_width_c_U->if_din(xFfast7x75682_U0_p_image_width_c_din);
    p_image_width_c_U->if_full_n(p_image_width_c_full_n);
    p_image_width_c_U->if_write(xFfast7x75682_U0_p_image_width_c_write);
    p_image_width_c_U->if_dout(p_image_width_c_dout);
    p_image_width_c_U->if_empty_n(p_image_width_c_empty_n);
    p_image_width_c_U->if_read(xFfastnms5781_U0_p_image_width_read);
    start_for_xFfastnpcA_U = new start_for_xFfastnpcA("start_for_xFfastnpcA_U");
    start_for_xFfastnpcA_U->clk(ap_clk);
    start_for_xFfastnpcA_U->reset(ap_rst);
    start_for_xFfastnpcA_U->if_read_ce(ap_var_for_const0);
    start_for_xFfastnpcA_U->if_write_ce(ap_var_for_const0);
    start_for_xFfastnpcA_U->if_din(start_for_xFfastnms5781_U0_din);
    start_for_xFfastnpcA_U->if_full_n(start_for_xFfastnms5781_U0_full_n);
    start_for_xFfastnpcA_U->if_write(xFfast7x75682_U0_start_write);
    start_for_xFfastnpcA_U->if_dout(start_for_xFfastnms5781_U0_dout);
    start_for_xFfastnpcA_U->if_empty_n(start_for_xFfastnms5781_U0_empty_n);
    start_for_xFfastnpcA_U->if_read(xFfastnms5781_U0_ap_ready);

    SC_METHOD(thread_ap_done);
    sensitive << ( xFfastnms5781_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( xFfast7x75682_U0_ap_idle );
    sensitive << ( xFfastnms5781_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( xFfast7x75682_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( xFfastnms5781_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( xFfast7x75682_U0_ap_ready );

    SC_METHOD(thread_p_dst_mat_data_V_din);
    sensitive << ( xFfastnms5781_U0_p_dst_mat_data_V_din );

    SC_METHOD(thread_p_dst_mat_data_V_write);
    sensitive << ( xFfastnms5781_U0_p_dst_mat_data_V_write );

    SC_METHOD(thread_p_src_mat_data_V_read);
    sensitive << ( xFfast7x75682_U0_p_src_mat_data_V_read );

    SC_METHOD(thread_start_for_xFfastnms5781_U0_din);

    SC_METHOD(thread_xFfast7x75682_U0_ap_continue);

    SC_METHOD(thread_xFfast7x75682_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_xFfastnms5781_U0_ap_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_xFfastnms5781_U0_ap_start);
    sensitive << ( start_for_xFfastnms5781_U0_empty_n );

    SC_METHOD(thread_xFfastnms5781_U0_start_full_n);

    SC_METHOD(thread_xFfastnms5781_U0_start_write);

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "xFFastCornerDetectio_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, p_src_mat_data_V_dout, "(port)p_src_mat_data_V_dout");
    sc_trace(mVcdFile, p_src_mat_data_V_empty_n, "(port)p_src_mat_data_V_empty_n");
    sc_trace(mVcdFile, p_src_mat_data_V_read, "(port)p_src_mat_data_V_read");
    sc_trace(mVcdFile, p_dst_mat_data_V_din, "(port)p_dst_mat_data_V_din");
    sc_trace(mVcdFile, p_dst_mat_data_V_full_n, "(port)p_dst_mat_data_V_full_n");
    sc_trace(mVcdFile, p_dst_mat_data_V_write, "(port)p_dst_mat_data_V_write");
    sc_trace(mVcdFile, p_image_height, "(port)p_image_height");
    sc_trace(mVcdFile, p_image_width, "(port)p_image_width");
    sc_trace(mVcdFile, p_threshold, "(port)p_threshold");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, p_image_height_ap_vld, "(port)p_image_height_ap_vld");
    sc_trace(mVcdFile, p_image_width_ap_vld, "(port)p_image_width_ap_vld");
    sc_trace(mVcdFile, p_threshold_ap_vld, "(port)p_threshold_ap_vld");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, xFfast7x75682_U0_ap_start, "xFfast7x75682_U0_ap_start");
    sc_trace(mVcdFile, xFfast7x75682_U0_ap_done, "xFfast7x75682_U0_ap_done");
    sc_trace(mVcdFile, xFfast7x75682_U0_ap_continue, "xFfast7x75682_U0_ap_continue");
    sc_trace(mVcdFile, xFfast7x75682_U0_ap_idle, "xFfast7x75682_U0_ap_idle");
    sc_trace(mVcdFile, xFfast7x75682_U0_ap_ready, "xFfast7x75682_U0_ap_ready");
    sc_trace(mVcdFile, xFfast7x75682_U0_start_out, "xFfast7x75682_U0_start_out");
    sc_trace(mVcdFile, xFfast7x75682_U0_start_write, "xFfast7x75682_U0_start_write");
    sc_trace(mVcdFile, xFfast7x75682_U0_p_src_mat_data_V_read, "xFfast7x75682_U0_p_src_mat_data_V_read");
    sc_trace(mVcdFile, xFfast7x75682_U0_p_dst_data_V_din, "xFfast7x75682_U0_p_dst_data_V_din");
    sc_trace(mVcdFile, xFfast7x75682_U0_p_dst_data_V_write, "xFfast7x75682_U0_p_dst_data_V_write");
    sc_trace(mVcdFile, xFfast7x75682_U0_p_image_height_c_din, "xFfast7x75682_U0_p_image_height_c_din");
    sc_trace(mVcdFile, xFfast7x75682_U0_p_image_height_c_write, "xFfast7x75682_U0_p_image_height_c_write");
    sc_trace(mVcdFile, xFfast7x75682_U0_p_image_width_c_din, "xFfast7x75682_U0_p_image_width_c_din");
    sc_trace(mVcdFile, xFfast7x75682_U0_p_image_width_c_write, "xFfast7x75682_U0_p_image_width_c_write");
    sc_trace(mVcdFile, xFfastnms5781_U0_ap_start, "xFfastnms5781_U0_ap_start");
    sc_trace(mVcdFile, xFfastnms5781_U0_ap_done, "xFfastnms5781_U0_ap_done");
    sc_trace(mVcdFile, xFfastnms5781_U0_ap_continue, "xFfastnms5781_U0_ap_continue");
    sc_trace(mVcdFile, xFfastnms5781_U0_ap_idle, "xFfastnms5781_U0_ap_idle");
    sc_trace(mVcdFile, xFfastnms5781_U0_ap_ready, "xFfastnms5781_U0_ap_ready");
    sc_trace(mVcdFile, xFfastnms5781_U0_p_dst_data_V_read, "xFfastnms5781_U0_p_dst_data_V_read");
    sc_trace(mVcdFile, xFfastnms5781_U0_p_dst_mat_data_V_din, "xFfastnms5781_U0_p_dst_mat_data_V_din");
    sc_trace(mVcdFile, xFfastnms5781_U0_p_dst_mat_data_V_write, "xFfastnms5781_U0_p_dst_mat_data_V_write");
    sc_trace(mVcdFile, xFfastnms5781_U0_p_image_height_read, "xFfastnms5781_U0_p_image_height_read");
    sc_trace(mVcdFile, xFfastnms5781_U0_p_image_width_read, "xFfastnms5781_U0_p_image_width_read");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, p_dst_data_V_full_n, "p_dst_data_V_full_n");
    sc_trace(mVcdFile, p_dst_data_V_dout, "p_dst_data_V_dout");
    sc_trace(mVcdFile, p_dst_data_V_empty_n, "p_dst_data_V_empty_n");
    sc_trace(mVcdFile, p_image_height_c_full_n, "p_image_height_c_full_n");
    sc_trace(mVcdFile, p_image_height_c_dout, "p_image_height_c_dout");
    sc_trace(mVcdFile, p_image_height_c_empty_n, "p_image_height_c_empty_n");
    sc_trace(mVcdFile, p_image_width_c_full_n, "p_image_width_c_full_n");
    sc_trace(mVcdFile, p_image_width_c_dout, "p_image_width_c_dout");
    sc_trace(mVcdFile, p_image_width_c_empty_n, "p_image_width_c_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, start_for_xFfastnms5781_U0_din, "start_for_xFfastnms5781_U0_din");
    sc_trace(mVcdFile, start_for_xFfastnms5781_U0_full_n, "start_for_xFfastnms5781_U0_full_n");
    sc_trace(mVcdFile, start_for_xFfastnms5781_U0_dout, "start_for_xFfastnms5781_U0_dout");
    sc_trace(mVcdFile, start_for_xFfastnms5781_U0_empty_n, "start_for_xFfastnms5781_U0_empty_n");
    sc_trace(mVcdFile, xFfastnms5781_U0_start_full_n, "xFfastnms5781_U0_start_full_n");
    sc_trace(mVcdFile, xFfastnms5781_U0_start_write, "xFfastnms5781_U0_start_write");
#endif

    }
}

xFFastCornerDetectio::~xFFastCornerDetectio() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete xFfast7x75682_U0;
    delete xFfastnms5781_U0;
    delete p_dst_data_V_U;
    delete p_image_height_c_U;
    delete p_image_width_c_U;
    delete start_for_xFfastnpcA_U;
}

void xFFastCornerDetectio::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void xFFastCornerDetectio::thread_ap_done() {
    ap_done = xFfastnms5781_U0_ap_done.read();
}

void xFFastCornerDetectio::thread_ap_idle() {
    ap_idle = (xFfast7x75682_U0_ap_idle.read() & xFfastnms5781_U0_ap_idle.read());
}

void xFFastCornerDetectio::thread_ap_ready() {
    ap_ready = xFfast7x75682_U0_ap_ready.read();
}

void xFFastCornerDetectio::thread_ap_sync_continue() {
    ap_sync_continue = ap_continue.read();
}

void xFFastCornerDetectio::thread_ap_sync_done() {
    ap_sync_done = xFfastnms5781_U0_ap_done.read();
}

void xFFastCornerDetectio::thread_ap_sync_ready() {
    ap_sync_ready = xFfast7x75682_U0_ap_ready.read();
}

void xFFastCornerDetectio::thread_p_dst_mat_data_V_din() {
    p_dst_mat_data_V_din = xFfastnms5781_U0_p_dst_mat_data_V_din.read();
}

void xFFastCornerDetectio::thread_p_dst_mat_data_V_write() {
    p_dst_mat_data_V_write = xFfastnms5781_U0_p_dst_mat_data_V_write.read();
}

void xFFastCornerDetectio::thread_p_src_mat_data_V_read() {
    p_src_mat_data_V_read = xFfast7x75682_U0_p_src_mat_data_V_read.read();
}

void xFFastCornerDetectio::thread_start_for_xFfastnms5781_U0_din() {
    start_for_xFfastnms5781_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void xFFastCornerDetectio::thread_xFfast7x75682_U0_ap_continue() {
    xFfast7x75682_U0_ap_continue = ap_const_logic_1;
}

void xFFastCornerDetectio::thread_xFfast7x75682_U0_ap_start() {
    xFfast7x75682_U0_ap_start = ap_start.read();
}

void xFFastCornerDetectio::thread_xFfastnms5781_U0_ap_continue() {
    xFfastnms5781_U0_ap_continue = ap_continue.read();
}

void xFFastCornerDetectio::thread_xFfastnms5781_U0_ap_start() {
    xFfastnms5781_U0_ap_start = start_for_xFfastnms5781_U0_empty_n.read();
}

void xFFastCornerDetectio::thread_xFfastnms5781_U0_start_full_n() {
    xFfastnms5781_U0_start_full_n = ap_const_logic_1;
}

void xFFastCornerDetectio::thread_xFfastnms5781_U0_start_write() {
    xFfastnms5781_U0_start_write = ap_const_logic_0;
}

}

