-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xFfastnms5781 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_dst_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_V_empty_n : IN STD_LOGIC;
    p_dst_data_V_read : OUT STD_LOGIC;
    p_dst_mat_data_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_mat_data_V_full_n : IN STD_LOGIC;
    p_dst_mat_data_V_write : OUT STD_LOGIC;
    p_image_height_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    p_image_height_empty_n : IN STD_LOGIC;
    p_image_height_read : OUT STD_LOGIC;
    p_image_width_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    p_image_width_empty_n : IN STD_LOGIC;
    p_image_width_read : OUT STD_LOGIC );
end;


architecture behav of xFfastnms5781 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv14_2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_dst_data_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln850_reg_1120 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln630_reg_1233 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln636_reg_1249 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_mat_data_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp1_iter4 : STD_LOGIC := '0';
    signal icmp_ln891_reg_1268 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_reg_1268_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_image_height_blk_n : STD_LOGIC;
    signal p_image_width_blk_n : STD_LOGIC;
    signal index_assign_reg_308 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_V_1_reg_318 : STD_LOGIC_VECTOR (11 downto 0);
    signal src_buf_1_1_0_i_i_reg_386 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_1_0_0_i_i_reg_398 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_0_1_0_i_i_reg_410 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_0_0_0_i_i_reg_422 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_2_0_0_i_i_reg_434 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf_2_1_0_i_i_reg_446 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_V_3_reg_458 : STD_LOGIC_VECTOR (12 downto 0);
    signal t_V_3_reg_458_pp1_iter1_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_state10_pp1_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op169_read_state11 : BOOLEAN;
    signal ap_block_state11_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_state12_pp1_stage0_iter2 : BOOLEAN;
    signal ap_block_state13_pp1_stage0_iter3 : BOOLEAN;
    signal ap_block_state14_pp1_stage0_iter4 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal p_image_height_read_reg_1043 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal p_image_width_read_reg_1048 : STD_LOGIC_VECTOR (11 downto 0);
    signal row_ind_2_V_load_reg_1055 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal row_ind_2_V_1_load_reg_1060 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_2_V_2_load_reg_1066 : STD_LOGIC_VECTOR (12 downto 0);
    signal init_row_ind_fu_485_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal init_buf_fu_518_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln836_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln850_fu_522_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln850_reg_1084 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln887_1_fu_525_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln887_1_reg_1091 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln887_fu_528_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln887_reg_1097 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln887_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln856_fu_537_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln856_reg_1106 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln321_fu_542_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_reg_1111 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_1_fu_546_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_1_reg_1115 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln850_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal col_V_1_fu_555_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal col_V_1_reg_1124 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal readind_val_fu_561_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal init_buf_1_fu_574_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln846_fu_580_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal col_V_fu_590_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal col_V_reg_1147 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal buf_0_V_addr_1_reg_1152 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln861_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln875_fu_603_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln875_reg_1168 : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_12_fu_608_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_12_reg_1173 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln875_1_fu_611_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln875_1_reg_1178 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln758_fu_623_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln758_reg_1183 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln875_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln887_1_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_1_reg_1193 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln544_fu_673_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln544_reg_1198 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln758_fu_685_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln758_reg_1203 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln758_1_fu_697_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln758_1_reg_1208 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln758_2_fu_709_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln758_2_reg_1213 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_2_fu_715_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_2_reg_1218 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_3_fu_719_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_3_reg_1223 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_4_fu_723_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_4_reg_1228 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln630_fu_727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln630_reg_1233_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln630_reg_1233_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln630_reg_1233_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal col_V_2_fu_732_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal col_V_2_reg_1237 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal icmp_ln887_2_fu_738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_2_reg_1242 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_2_reg_1242_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_2_reg_1242_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln636_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln769_fu_873_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln769_reg_1275 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp1_iter3 : STD_LOGIC := '0';
    signal select_ln769_1_fu_880_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln769_1_reg_1280 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln769_2_fu_887_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln769_2_reg_1285 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln895_3_fu_894_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_3_reg_1290 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_4_fu_900_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_4_reg_1295 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_5_fu_906_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_5_reg_1300 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_6_fu_912_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_6_reg_1305 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln883_6_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln883_6_reg_1310 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln791_fu_972_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln791_reg_1315 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln791_1_fu_979_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln791_1_reg_1320 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln791_2_fu_986_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln791_2_reg_1325 : STD_LOGIC_VECTOR (7 downto 0);
    signal row_V_fu_1013_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state4 : STD_LOGIC;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state10 : STD_LOGIC;
    signal ap_enable_reg_pp1_iter2 : STD_LOGIC := '0';
    signal buf_0_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_0_V_ce0 : STD_LOGIC;
    signal buf_0_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_0_V_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_0_V_ce1 : STD_LOGIC;
    signal buf_0_V_we1 : STD_LOGIC;
    signal buf_0_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_1_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_1_V_ce0 : STD_LOGIC;
    signal buf_1_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_1_V_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_1_V_ce1 : STD_LOGIC;
    signal buf_1_V_we1 : STD_LOGIC;
    signal buf_2_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_2_V_ce0 : STD_LOGIC;
    signal buf_2_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_2_V_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal buf_2_V_ce1 : STD_LOGIC;
    signal buf_2_V_we1 : STD_LOGIC;
    signal ap_phi_mux_i_op_assign_phi_fu_269_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_op_assign_reg_265 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvars_iv_i_i_reg_276 : STD_LOGIC_VECTOR (31 downto 0);
    signal readind_val_0_i_i_reg_286 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_op_assign_1_reg_298 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_t_V_1_phi_fu_322_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal t_V_reg_330 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal row_ind_1_V_1_reg_341 : STD_LOGIC_VECTOR (12 downto 0);
    signal zero_ind_V_reg_362 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_0_V_reg_351 : STD_LOGIC_VECTOR (12 downto 0);
    signal t_V_2_reg_374 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_t_V_3_phi_fu_462_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln544_fu_567_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_1_fu_596_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_2_fu_748_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_3_fu_755_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal row_ind_2_V_fu_98 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_0_V_2_fu_491_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_2_V_1_fu_102 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_2_V_2_fu_106 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_2_V_3_fu_110 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal tmp_1_fu_627_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln758_fu_617_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln887_2_fu_639_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_fu_658_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_1_fu_663_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln895_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_677_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1354_fu_669_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln895_1_fu_691_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_2_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_768_p5 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln321_5_fu_779_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_783_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_795_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_813_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_825_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_843_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_855_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_cop_0_V_fu_806_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_cop_1_V_fu_836_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_cop_2_V_fu_866_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln895_7_fu_918_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_8_fu_924_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_10_fu_936_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln883_4_fu_954_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_9_fu_930_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln883_5_fu_960_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln883_3_fu_948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln883_1_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln883_fu_993_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln883_2_fu_1001_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;

    component fast_accel_mux_32ncg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component fast_accel_mux_32ocq IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component xFfast7x75682_bufbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    buf_0_V_U : component xFfast7x75682_bufbkb
    generic map (
        DataWidth => 8,
        AddressRange => 3840,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_0_V_address0,
        ce0 => buf_0_V_ce0,
        q0 => buf_0_V_q0,
        address1 => buf_0_V_address1,
        ce1 => buf_0_V_ce1,
        we1 => buf_0_V_we1,
        d1 => buf_0_V_d1);

    buf_1_V_U : component xFfast7x75682_bufbkb
    generic map (
        DataWidth => 8,
        AddressRange => 3840,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_1_V_address0,
        ce0 => buf_1_V_ce0,
        q0 => buf_1_V_q0,
        address1 => buf_1_V_address1,
        ce1 => buf_1_V_ce1,
        we1 => buf_1_V_we1,
        d1 => p_dst_data_V_dout);

    buf_2_V_U : component xFfast7x75682_bufbkb
    generic map (
        DataWidth => 8,
        AddressRange => 3840,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2_V_address0,
        ce0 => buf_2_V_ce0,
        q0 => buf_2_V_q0,
        address1 => buf_2_V_address1,
        ce1 => buf_2_V_ce1,
        we1 => buf_2_V_we1,
        d1 => p_dst_data_V_dout);

    fast_accel_mux_32ncg_U41 : component fast_accel_mux_32ncg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_0_V_q0,
        din1 => buf_1_V_q0,
        din2 => buf_2_V_q0,
        din3 => trunc_ln321_1_reg_1115,
        dout => tmp_1_fu_627_p5);

    fast_accel_mux_32ocq_U42 : component fast_accel_mux_32ocq
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 13,
        din1_WIDTH => 13,
        din2_WIDTH => 13,
        din3_WIDTH => 2,
        dout_WIDTH => 13)
    port map (
        din0 => zero_ind_V_reg_362,
        din1 => row_ind_0_V_reg_351,
        din2 => row_ind_1_V_1_reg_341,
        din3 => trunc_ln544_reg_1198,
        dout => tmp_2_fu_768_p5);

    fast_accel_mux_32ncg_U43 : component fast_accel_mux_32ncg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_0_V_q0,
        din1 => buf_1_V_q0,
        din2 => buf_2_V_q0,
        din3 => trunc_ln321_5_fu_779_p1,
        dout => tmp_3_fu_783_p5);

    fast_accel_mux_32ncg_U44 : component fast_accel_mux_32ncg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_0_V_q0,
        din1 => buf_1_V_q0,
        din2 => buf_2_V_q0,
        din3 => trunc_ln321_3_reg_1223,
        dout => tmp_4_fu_795_p5);

    fast_accel_mux_32ncg_U45 : component fast_accel_mux_32ncg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_0_V_q0,
        din1 => buf_1_V_q0,
        din2 => buf_2_V_q0,
        din3 => trunc_ln321_5_fu_779_p1,
        dout => tmp_5_fu_813_p5);

    fast_accel_mux_32ncg_U46 : component fast_accel_mux_32ncg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_0_V_q0,
        din1 => buf_1_V_q0,
        din2 => buf_2_V_q0,
        din3 => trunc_ln321_4_reg_1228,
        dout => tmp_6_fu_825_p5);

    fast_accel_mux_32ncg_U47 : component fast_accel_mux_32ncg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_0_V_q0,
        din1 => buf_1_V_q0,
        din2 => buf_2_V_q0,
        din3 => trunc_ln321_5_fu_779_p1,
        dout => tmp_7_fu_843_p5);

    fast_accel_mux_32ncg_U48 : component fast_accel_mux_32ncg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_0_V_q0,
        din1 => buf_1_V_q0,
        din2 => buf_2_V_q0,
        din3 => trunc_ln321_2_reg_1218,
        dout => tmp_8_fu_855_p5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln887_fu_532_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state4);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((icmp_ln887_fu_532_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state10))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp1_exit_iter0_state10)) then 
                        ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state10);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
                elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    ap_enable_reg_pp1_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_op_assign_1_reg_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln836_fu_479_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_op_assign_1_reg_298 <= init_buf_fu_518_p1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_op_assign_1_reg_298 <= init_buf_1_fu_574_p2;
            end if; 
        end if;
    end process;

    i_op_assign_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln836_fu_479_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_op_assign_reg_265 <= init_row_ind_fu_485_p2;
            elsif ((not(((p_image_width_empty_n = ap_const_logic_0) or (p_image_height_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_op_assign_reg_265 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    index_assign_reg_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln850_fu_549_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                index_assign_reg_308 <= readind_val_fu_561_p2;
            elsif (((icmp_ln887_fu_532_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                index_assign_reg_308 <= readind_val_0_i_i_reg_286;
            end if; 
        end if;
    end process;

    indvars_iv_i_i_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln836_fu_479_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                indvars_iv_i_i_reg_276 <= zext_ln850_fu_522_p1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                indvars_iv_i_i_reg_276 <= add_ln846_fu_580_p2;
            end if; 
        end if;
    end process;

    readind_val_0_i_i_reg_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln836_fu_479_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                readind_val_0_i_i_reg_286 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                readind_val_0_i_i_reg_286 <= add_ln856_reg_1106;
            end if; 
        end if;
    end process;

    row_ind_0_V_reg_351_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                row_ind_0_V_reg_351 <= row_ind_1_V_1_reg_341;
            elsif (((icmp_ln861_fu_585_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                row_ind_0_V_reg_351 <= row_ind_2_V_1_load_reg_1060;
            end if; 
        end if;
    end process;

    row_ind_1_V_1_reg_341_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                row_ind_1_V_1_reg_341 <= zero_ind_V_reg_362;
            elsif (((icmp_ln861_fu_585_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                row_ind_1_V_1_reg_341 <= row_ind_2_V_2_load_reg_1066;
            end if; 
        end if;
    end process;

    src_buf_0_0_0_i_i_reg_422_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                src_buf_0_0_0_i_i_reg_422 <= select_ln791_reg_1315;
            elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                src_buf_0_0_0_i_i_reg_422 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    src_buf_0_1_0_i_i_reg_410_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                src_buf_0_1_0_i_i_reg_410 <= select_ln769_reg_1275;
            elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                src_buf_0_1_0_i_i_reg_410 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    src_buf_1_0_0_i_i_reg_398_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                src_buf_1_0_0_i_i_reg_398 <= select_ln791_1_reg_1320;
            elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                src_buf_1_0_0_i_i_reg_398 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    src_buf_1_1_0_i_i_reg_386_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                src_buf_1_1_0_i_i_reg_386 <= select_ln769_1_reg_1280;
            elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                src_buf_1_1_0_i_i_reg_386 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    src_buf_2_0_0_i_i_reg_434_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                src_buf_2_0_0_i_i_reg_434 <= select_ln791_2_reg_1325;
            elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                src_buf_2_0_0_i_i_reg_434 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    src_buf_2_1_0_i_i_reg_446_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                src_buf_2_1_0_i_i_reg_446 <= select_ln769_2_reg_1285;
            elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                src_buf_2_1_0_i_i_reg_446 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    t_V_1_reg_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln850_reg_1120 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                t_V_1_reg_318 <= col_V_1_reg_1124;
            elsif (((icmp_ln887_fu_532_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                t_V_1_reg_318 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    t_V_2_reg_374_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                t_V_2_reg_374 <= row_V_fu_1013_p2;
            elsif (((icmp_ln861_fu_585_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                t_V_2_reg_374 <= ap_const_lv13_1;
            end if; 
        end if;
    end process;

    t_V_3_reg_458_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                t_V_3_reg_458 <= col_V_2_reg_1237;
            elsif (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                t_V_3_reg_458 <= ap_const_lv13_0;
            end if; 
        end if;
    end process;

    t_V_reg_330_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln887_fu_532_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                t_V_reg_330 <= ap_const_lv12_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                t_V_reg_330 <= col_V_reg_1147;
            end if; 
        end if;
    end process;

    zero_ind_V_reg_362_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                zero_ind_V_reg_362 <= row_ind_0_V_reg_351;
            elsif (((icmp_ln861_fu_585_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                zero_ind_V_reg_362 <= row_ind_2_V_load_reg_1055;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln887_fu_532_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                add_ln856_reg_1106 <= add_ln856_fu_537_p2;
                trunc_ln321_reg_1111 <= trunc_ln321_fu_542_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln861_fu_585_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                add_ln875_1_reg_1178 <= add_ln875_1_fu_611_p2;
                add_ln875_reg_1168 <= add_ln875_fu_603_p2;
                    empty_12_reg_1173(11 downto 0) <= empty_12_fu_608_p1(11 downto 0);
                sext_ln758_reg_1183 <= sext_ln758_fu_623_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_fu_727_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                and_ln636_reg_1249 <= and_ln636_fu_743_p2;
                icmp_ln887_2_reg_1242 <= icmp_ln887_2_fu_738_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln875_fu_643_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                and_ln758_1_reg_1208 <= and_ln758_1_fu_697_p2;
                and_ln758_2_reg_1213 <= and_ln758_2_fu_709_p2;
                and_ln758_reg_1203 <= and_ln758_fu_685_p2;
                icmp_ln887_1_reg_1193 <= icmp_ln887_1_fu_648_p2;
                trunc_ln321_2_reg_1218 <= trunc_ln321_2_fu_715_p1;
                trunc_ln321_3_reg_1223 <= trunc_ln321_3_fu_719_p1;
                trunc_ln321_4_reg_1228 <= trunc_ln321_4_fu_723_p1;
                trunc_ln544_reg_1198 <= trunc_ln544_fu_673_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                and_ln883_6_reg_1310 <= and_ln883_6_fu_966_p2;
                icmp_ln895_3_reg_1290 <= icmp_ln895_3_fu_894_p2;
                icmp_ln895_4_reg_1295 <= icmp_ln895_4_fu_900_p2;
                icmp_ln895_5_reg_1300 <= icmp_ln895_5_fu_906_p2;
                icmp_ln895_6_reg_1305 <= icmp_ln895_6_fu_912_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln861_fu_585_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                buf_0_V_addr_1_reg_1152 <= zext_ln544_1_fu_596_p1(12 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                col_V_1_reg_1124 <= col_V_1_fu_555_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                col_V_2_reg_1237 <= col_V_2_fu_732_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                col_V_reg_1147 <= col_V_fu_590_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                icmp_ln630_reg_1233 <= icmp_ln630_fu_727_p2;
                icmp_ln630_reg_1233_pp1_iter1_reg <= icmp_ln630_reg_1233;
                icmp_ln887_2_reg_1242_pp1_iter1_reg <= icmp_ln887_2_reg_1242;
                t_V_3_reg_458_pp1_iter1_reg <= t_V_3_reg_458;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp1_stage0_11001)) then
                icmp_ln630_reg_1233_pp1_iter2_reg <= icmp_ln630_reg_1233_pp1_iter1_reg;
                icmp_ln630_reg_1233_pp1_iter3_reg <= icmp_ln630_reg_1233_pp1_iter2_reg;
                icmp_ln887_2_reg_1242_pp1_iter2_reg <= icmp_ln887_2_reg_1242_pp1_iter1_reg;
                icmp_ln891_reg_1268_pp1_iter3_reg <= icmp_ln891_reg_1268;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln850_reg_1120 <= icmp_ln850_fu_549_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                icmp_ln891_reg_1268 <= icmp_ln891_fu_762_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((p_image_width_empty_n = ap_const_logic_0) or (p_image_height_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_image_height_read_reg_1043 <= p_image_height_dout;
                p_image_width_read_reg_1048 <= p_image_width_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln836_fu_479_p2 = ap_const_lv1_0) and (ap_phi_mux_i_op_assign_phi_fu_269_p4 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    row_ind_2_V_1_fu_102(1 downto 0) <= row_ind_0_V_2_fu_491_p1(1 downto 0);
                    row_ind_2_V_3_fu_110(1 downto 0) <= row_ind_0_V_2_fu_491_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    row_ind_2_V_1_load_reg_1060(1 downto 0) <= row_ind_2_V_1_fu_102(1 downto 0);
                    row_ind_2_V_2_load_reg_1066(1 downto 0) <= row_ind_2_V_2_fu_106(1 downto 0);
                    row_ind_2_V_load_reg_1055(1 downto 0) <= row_ind_2_V_fu_98(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_phi_mux_i_op_assign_phi_fu_269_p4 = ap_const_lv2_1)) and not((ap_phi_mux_i_op_assign_phi_fu_269_p4 = ap_const_lv2_0)) and (icmp_ln836_fu_479_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    row_ind_2_V_2_fu_106(1 downto 0) <= row_ind_0_V_2_fu_491_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln836_fu_479_p2 = ap_const_lv1_0) and (ap_phi_mux_i_op_assign_phi_fu_269_p4 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    row_ind_2_V_fu_98(1 downto 0) <= row_ind_0_V_2_fu_491_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln630_reg_1233_pp1_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                select_ln769_1_reg_1280 <= select_ln769_1_fu_880_p3;
                select_ln769_2_reg_1285 <= select_ln769_2_fu_887_p3;
                select_ln769_reg_1275 <= select_ln769_fu_873_p3;
                select_ln791_1_reg_1320 <= select_ln791_1_fu_979_p3;
                select_ln791_2_reg_1325 <= select_ln791_2_fu_986_p3;
                select_ln791_reg_1315 <= select_ln791_fu_972_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln887_fu_532_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                trunc_ln321_1_reg_1115 <= trunc_ln321_1_fu_546_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln836_fu_479_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    zext_ln850_reg_1084(11 downto 0) <= zext_ln850_fu_522_p1(11 downto 0);
                    zext_ln887_1_reg_1091(11 downto 0) <= zext_ln887_1_fu_525_p1(11 downto 0);
                    zext_ln887_reg_1097(1 downto 0) <= zext_ln887_fu_528_p1(1 downto 0);
            end if;
        end if;
    end process;
    row_ind_2_V_load_reg_1055(12 downto 2) <= "00000000000";
    row_ind_2_V_1_load_reg_1060(12 downto 2) <= "00000000000";
    row_ind_2_V_2_load_reg_1066(12 downto 2) <= "00000000000";
    zext_ln850_reg_1084(31 downto 12) <= "00000000000000000000";
    zext_ln887_1_reg_1091(12) <= '0';
    zext_ln887_reg_1097(31 downto 2) <= "000000000000000000000000000000";
    empty_12_reg_1173(12) <= '0';
    row_ind_2_V_fu_98(12 downto 2) <= "00000000000";
    row_ind_2_V_1_fu_102(12 downto 2) <= "00000000000";
    row_ind_2_V_2_fu_106(12 downto 2) <= "00000000000";
    row_ind_2_V_3_fu_110(12 downto 2) <= "00000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, p_image_height_empty_n, p_image_width_empty_n, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, ap_CS_fsm_state2, icmp_ln836_fu_479_p2, icmp_ln887_fu_532_p2, ap_CS_fsm_state3, icmp_ln850_fu_549_p2, ap_enable_reg_pp0_iter0, ap_CS_fsm_state7, icmp_ln861_fu_585_p2, icmp_ln875_fu_643_p2, ap_CS_fsm_state9, icmp_ln630_fu_727_p2, ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter3, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((p_image_width_empty_n = ap_const_logic_0) or (p_image_height_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln836_fu_479_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln887_fu_532_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((icmp_ln850_fu_549_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((icmp_ln850_fu_549_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln861_fu_585_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state9 => 
                if (((icmp_ln875_fu_643_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if ((not(((icmp_ln630_fu_727_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) and not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter3 = ap_const_logic_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter3 = ap_const_logic_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1)) or ((icmp_ln630_fu_727_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln758_fu_617_p2 <= std_logic_vector(unsigned(empty_12_fu_608_p1) + unsigned(ap_const_lv13_1FFF));
    add_ln846_fu_580_p2 <= std_logic_vector(unsigned(zext_ln850_reg_1084) + unsigned(indvars_iv_i_i_reg_276));
    add_ln856_fu_537_p2 <= std_logic_vector(unsigned(zext_ln850_reg_1084) + unsigned(readind_val_0_i_i_reg_286));
    add_ln875_1_fu_611_p2 <= std_logic_vector(unsigned(empty_12_fu_608_p1) + unsigned(ap_const_lv13_1));
    add_ln875_fu_603_p2 <= std_logic_vector(unsigned(zext_ln887_1_reg_1091) + unsigned(ap_const_lv13_1));
    and_ln636_fu_743_p2 <= (icmp_ln887_2_fu_738_p2 and icmp_ln887_1_reg_1193);
    and_ln758_1_fu_697_p2 <= (icmp_ln895_fu_653_p2 and icmp_ln895_1_fu_691_p2);
    and_ln758_2_fu_709_p2 <= (icmp_ln895_fu_653_p2 and icmp_ln895_2_fu_703_p2);
    and_ln758_fu_685_p2 <= (tmp_fu_677_p3 and icmp_ln895_fu_653_p2);
    and_ln883_1_fu_997_p2 <= (icmp_ln895_6_reg_1305 and icmp_ln895_5_reg_1300);
    and_ln883_2_fu_1001_p2 <= (and_ln883_fu_993_p2 and and_ln883_1_fu_997_p2);
    and_ln883_3_fu_948_p2 <= (icmp_ln895_8_fu_924_p2 and icmp_ln895_7_fu_918_p2);
    and_ln883_4_fu_954_p2 <= (icmp_ln895_10_fu_936_p2 and icmp_ln883_fu_942_p2);
    and_ln883_5_fu_960_p2 <= (icmp_ln895_9_fu_930_p2 and and_ln883_4_fu_954_p2);
    and_ln883_6_fu_966_p2 <= (and_ln883_5_fu_960_p2 and and_ln883_3_fu_948_p2);
    and_ln883_fu_993_p2 <= (icmp_ln895_4_reg_1295 and icmp_ln895_3_reg_1290);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(8);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state15 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(6);
    ap_CS_fsm_state9 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(p_dst_data_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln850_reg_1120)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln850_reg_1120 = ap_const_lv1_0) and (p_dst_data_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_dst_data_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln850_reg_1120)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln850_reg_1120 = ap_const_lv1_0) and (p_dst_data_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(p_dst_data_V_empty_n, p_dst_mat_data_V_full_n, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, icmp_ln891_reg_1268_pp1_iter3_reg, ap_predicate_op169_read_state11)
    begin
                ap_block_pp1_stage0_01001 <= (((icmp_ln891_reg_1268_pp1_iter3_reg = ap_const_lv1_0) and (p_dst_mat_data_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1)) or ((p_dst_data_V_empty_n = ap_const_logic_0) and (ap_predicate_op169_read_state11 = ap_const_boolean_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(p_dst_data_V_empty_n, p_dst_mat_data_V_full_n, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, icmp_ln891_reg_1268_pp1_iter3_reg, ap_predicate_op169_read_state11)
    begin
                ap_block_pp1_stage0_11001 <= (((icmp_ln891_reg_1268_pp1_iter3_reg = ap_const_lv1_0) and (p_dst_mat_data_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1)) or ((p_dst_data_V_empty_n = ap_const_logic_0) and (ap_predicate_op169_read_state11 = ap_const_boolean_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(p_dst_data_V_empty_n, p_dst_mat_data_V_full_n, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, icmp_ln891_reg_1268_pp1_iter3_reg, ap_predicate_op169_read_state11)
    begin
                ap_block_pp1_stage0_subdone <= (((icmp_ln891_reg_1268_pp1_iter3_reg = ap_const_lv1_0) and (p_dst_mat_data_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1)) or ((p_dst_data_V_empty_n = ap_const_logic_0) and (ap_predicate_op169_read_state11 = ap_const_boolean_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1)));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, p_image_height_empty_n, p_image_width_empty_n)
    begin
                ap_block_state1 <= ((p_image_width_empty_n = ap_const_logic_0) or (p_image_height_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state10_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state11_pp1_stage0_iter1_assign_proc : process(p_dst_data_V_empty_n, ap_predicate_op169_read_state11)
    begin
                ap_block_state11_pp1_stage0_iter1 <= ((p_dst_data_V_empty_n = ap_const_logic_0) and (ap_predicate_op169_read_state11 = ap_const_boolean_1));
    end process;

        ap_block_state12_pp1_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp1_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state14_pp1_stage0_iter4_assign_proc : process(p_dst_mat_data_V_full_n, icmp_ln891_reg_1268_pp1_iter3_reg)
    begin
                ap_block_state14_pp1_stage0_iter4 <= ((icmp_ln891_reg_1268_pp1_iter3_reg = ap_const_lv1_0) and (p_dst_mat_data_V_full_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter1_assign_proc : process(p_dst_data_V_empty_n, icmp_ln850_reg_1120)
    begin
                ap_block_state5_pp0_stage0_iter1 <= ((icmp_ln850_reg_1120 = ap_const_lv1_0) and (p_dst_data_V_empty_n = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state4_assign_proc : process(icmp_ln850_fu_549_p2)
    begin
        if ((icmp_ln850_fu_549_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state10_assign_proc : process(icmp_ln630_fu_727_p2)
    begin
        if ((icmp_ln630_fu_727_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state10 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state10 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, icmp_ln875_fu_643_p2, ap_CS_fsm_state9)
    begin
        if (((icmp_ln875_fu_643_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter3, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_enable_reg_pp1_iter4 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_i_op_assign_phi_fu_269_p4 <= i_op_assign_reg_265;

    ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, src_buf_0_0_0_i_i_reg_422, icmp_ln630_reg_1233_pp1_iter3_reg, select_ln791_reg_1315)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4 <= select_ln791_reg_1315;
        else 
            ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4 <= src_buf_0_0_0_i_i_reg_422;
        end if; 
    end process;


    ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, src_buf_0_1_0_i_i_reg_410, icmp_ln630_reg_1233_pp1_iter3_reg, select_ln769_reg_1275)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4 <= select_ln769_reg_1275;
        else 
            ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4 <= src_buf_0_1_0_i_i_reg_410;
        end if; 
    end process;


    ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, src_buf_1_0_0_i_i_reg_398, icmp_ln630_reg_1233_pp1_iter3_reg, select_ln791_1_reg_1320)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4 <= select_ln791_1_reg_1320;
        else 
            ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4 <= src_buf_1_0_0_i_i_reg_398;
        end if; 
    end process;


    ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, src_buf_1_1_0_i_i_reg_386, icmp_ln630_reg_1233_pp1_iter3_reg, select_ln769_1_reg_1280)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 <= select_ln769_1_reg_1280;
        else 
            ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 <= src_buf_1_1_0_i_i_reg_386;
        end if; 
    end process;


    ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, src_buf_2_0_0_i_i_reg_434, icmp_ln630_reg_1233_pp1_iter3_reg, select_ln791_2_reg_1325)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4 <= select_ln791_2_reg_1325;
        else 
            ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4 <= src_buf_2_0_0_i_i_reg_434;
        end if; 
    end process;


    ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, src_buf_2_1_0_i_i_reg_446, icmp_ln630_reg_1233_pp1_iter3_reg, select_ln769_2_reg_1285)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln630_reg_1233_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4 <= select_ln769_2_reg_1285;
        else 
            ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4 <= src_buf_2_1_0_i_i_reg_446;
        end if; 
    end process;


    ap_phi_mux_t_V_1_phi_fu_322_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln850_reg_1120, t_V_1_reg_318, col_V_1_reg_1124)
    begin
        if (((icmp_ln850_reg_1120 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_t_V_1_phi_fu_322_p4 <= col_V_1_reg_1124;
        else 
            ap_phi_mux_t_V_1_phi_fu_322_p4 <= t_V_1_reg_318;
        end if; 
    end process;


    ap_phi_mux_t_V_3_phi_fu_462_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln630_reg_1233, t_V_3_reg_458, col_V_2_reg_1237)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln630_reg_1233 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_t_V_3_phi_fu_462_p4 <= col_V_2_reg_1237;
        else 
            ap_phi_mux_t_V_3_phi_fu_462_p4 <= t_V_3_reg_458;
        end if; 
    end process;


    ap_predicate_op169_read_state11_assign_proc : process(icmp_ln630_reg_1233, and_ln636_reg_1249)
    begin
                ap_predicate_op169_read_state11 <= ((ap_const_lv1_1 = and_ln636_reg_1249) and (icmp_ln630_reg_1233 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(icmp_ln875_fu_643_p2, ap_CS_fsm_state9)
    begin
        if (((icmp_ln875_fu_643_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    buf_0_V_address0_assign_proc : process(ap_block_pp1_stage0, ap_CS_fsm_state7, ap_enable_reg_pp1_iter2, zext_ln544_1_fu_596_p1, zext_ln544_3_fu_755_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1))) then 
            buf_0_V_address0 <= zext_ln544_3_fu_755_p1(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_0_V_address0 <= zext_ln544_1_fu_596_p1(12 - 1 downto 0);
        else 
            buf_0_V_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_0_V_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, buf_0_V_addr_1_reg_1152, ap_CS_fsm_state8, zext_ln544_fu_567_p1, zext_ln544_2_fu_748_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            buf_0_V_address1 <= zext_ln544_2_fu_748_p1(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_0_V_address1 <= buf_0_V_addr_1_reg_1152;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buf_0_V_address1 <= zext_ln544_fu_567_p1(12 - 1 downto 0);
        else 
            buf_0_V_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_0_V_ce0_assign_proc : process(ap_block_pp1_stage0_11001, ap_CS_fsm_state7, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)))) then 
            buf_0_V_ce0 <= ap_const_logic_1;
        else 
            buf_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_0_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_0_V_ce1 <= ap_const_logic_1;
        else 
            buf_0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_0_V_d1_assign_proc : process(p_dst_data_V_dout, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, ap_CS_fsm_state8, tmp_1_fu_627_p5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_0_V_d1 <= tmp_1_fu_627_p5;
        elsif ((((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buf_0_V_d1 <= p_dst_data_V_dout;
        else 
            buf_0_V_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_0_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln630_reg_1233, and_ln636_reg_1249, ap_block_pp1_stage0_11001, trunc_ln321_reg_1111, ap_block_pp0_stage0_11001, trunc_ln321_2_reg_1218, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_lv1_1 = and_ln636_reg_1249) and (icmp_ln630_reg_1233 = ap_const_lv1_0) and (trunc_ln321_2_reg_1218 = ap_const_lv2_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln321_reg_1111 = ap_const_lv2_0)))) then 
            buf_0_V_we1 <= ap_const_logic_1;
        else 
            buf_0_V_we1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_1_V_address0_assign_proc : process(ap_block_pp1_stage0, ap_CS_fsm_state7, ap_enable_reg_pp1_iter2, zext_ln544_1_fu_596_p1, zext_ln544_3_fu_755_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1))) then 
            buf_1_V_address0 <= zext_ln544_3_fu_755_p1(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_1_V_address0 <= zext_ln544_1_fu_596_p1(12 - 1 downto 0);
        else 
            buf_1_V_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_1_V_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, zext_ln544_fu_567_p1, zext_ln544_2_fu_748_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            buf_1_V_address1 <= zext_ln544_2_fu_748_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buf_1_V_address1 <= zext_ln544_fu_567_p1(12 - 1 downto 0);
        else 
            buf_1_V_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_1_V_ce0_assign_proc : process(ap_block_pp1_stage0_11001, ap_CS_fsm_state7, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)))) then 
            buf_1_V_ce0 <= ap_const_logic_1;
        else 
            buf_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_1_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_1_V_ce1 <= ap_const_logic_1;
        else 
            buf_1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_1_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln630_reg_1233, and_ln636_reg_1249, ap_block_pp1_stage0_11001, trunc_ln321_reg_1111, ap_block_pp0_stage0_11001, trunc_ln321_2_reg_1218)
    begin
        if ((((ap_const_lv1_1 = and_ln636_reg_1249) and (icmp_ln630_reg_1233 = ap_const_lv1_0) and (trunc_ln321_2_reg_1218 = ap_const_lv2_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln321_reg_1111 = ap_const_lv2_1)))) then 
            buf_1_V_we1 <= ap_const_logic_1;
        else 
            buf_1_V_we1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2_V_address0_assign_proc : process(ap_block_pp1_stage0, ap_CS_fsm_state7, ap_enable_reg_pp1_iter2, zext_ln544_1_fu_596_p1, zext_ln544_3_fu_755_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1))) then 
            buf_2_V_address0 <= zext_ln544_3_fu_755_p1(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_2_V_address0 <= zext_ln544_1_fu_596_p1(12 - 1 downto 0);
        else 
            buf_2_V_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_2_V_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, zext_ln544_fu_567_p1, zext_ln544_2_fu_748_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            buf_2_V_address1 <= zext_ln544_2_fu_748_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buf_2_V_address1 <= zext_ln544_fu_567_p1(12 - 1 downto 0);
        else 
            buf_2_V_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    buf_2_V_ce0_assign_proc : process(ap_block_pp1_stage0_11001, ap_CS_fsm_state7, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_enable_reg_pp1_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)))) then 
            buf_2_V_ce0 <= ap_const_logic_1;
        else 
            buf_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_2_V_ce1 <= ap_const_logic_1;
        else 
            buf_2_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln630_reg_1233, and_ln636_reg_1249, ap_block_pp1_stage0_11001, trunc_ln321_reg_1111, ap_block_pp0_stage0_11001, trunc_ln321_2_reg_1218)
    begin
        if (((not((trunc_ln321_2_reg_1218 = ap_const_lv2_0)) and not((trunc_ln321_2_reg_1218 = ap_const_lv2_1)) and (ap_const_lv1_1 = and_ln636_reg_1249) and (icmp_ln630_reg_1233 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or (not((trunc_ln321_reg_1111 = ap_const_lv2_0)) and not((trunc_ln321_reg_1111 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_2_V_we1 <= ap_const_logic_1;
        else 
            buf_2_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_cop_0_V_fu_806_p3 <= 
        tmp_3_fu_783_p5 when (and_ln758_reg_1203(0) = '1') else 
        tmp_4_fu_795_p5;
    buf_cop_1_V_fu_836_p3 <= 
        tmp_5_fu_813_p5 when (and_ln758_1_reg_1208(0) = '1') else 
        tmp_6_fu_825_p5;
    buf_cop_2_V_fu_866_p3 <= 
        tmp_7_fu_843_p5 when (and_ln758_2_reg_1213(0) = '1') else 
        tmp_8_fu_855_p5;
    col_V_1_fu_555_p2 <= std_logic_vector(unsigned(ap_phi_mux_t_V_1_phi_fu_322_p4) + unsigned(ap_const_lv12_1));
    col_V_2_fu_732_p2 <= std_logic_vector(unsigned(ap_phi_mux_t_V_3_phi_fu_462_p4) + unsigned(ap_const_lv13_1));
    col_V_fu_590_p2 <= std_logic_vector(unsigned(t_V_reg_330) + unsigned(ap_const_lv12_1));
    empty_12_fu_608_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_image_height_read_reg_1043),13));
    icmp_ln630_fu_727_p2 <= "1" when (ap_phi_mux_t_V_3_phi_fu_462_p4 = add_ln875_reg_1168) else "0";
    icmp_ln836_fu_479_p2 <= "1" when (i_op_assign_reg_265 = ap_const_lv2_3) else "0";
    icmp_ln850_fu_549_p2 <= "1" when (index_assign_reg_308 = indvars_iv_i_i_reg_276) else "0";
    icmp_ln861_fu_585_p2 <= "1" when (t_V_reg_330 = p_image_width_read_reg_1048) else "0";
    icmp_ln875_fu_643_p2 <= "1" when (t_V_2_reg_374 = add_ln875_1_reg_1178) else "0";
    icmp_ln883_fu_942_p2 <= "0" when (ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 = ap_const_lv8_0) else "1";
    icmp_ln887_1_fu_648_p2 <= "1" when (unsigned(t_V_2_reg_374) < unsigned(empty_12_reg_1173)) else "0";
    icmp_ln887_2_fu_738_p2 <= "1" when (unsigned(ap_phi_mux_t_V_3_phi_fu_462_p4) < unsigned(zext_ln887_1_reg_1091)) else "0";
    icmp_ln887_fu_532_p2 <= "1" when (signed(i_op_assign_1_reg_298) < signed(zext_ln887_reg_1097)) else "0";
    icmp_ln891_fu_762_p2 <= "1" when (t_V_3_reg_458_pp1_iter1_reg = ap_const_lv13_0) else "0";
    icmp_ln895_10_fu_936_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4) > unsigned(select_ln769_2_fu_887_p3)) else "0";
    icmp_ln895_1_fu_691_p2 <= "1" when (signed(trunc_ln1354_fu_669_p1) < signed(ap_const_lv13_1)) else "0";
    icmp_ln895_2_fu_703_p2 <= "1" when (signed(ret_V_fu_658_p2) > signed(ap_const_lv14_0)) else "0";
    icmp_ln895_3_fu_894_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4) > unsigned(ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4)) else "0";
    icmp_ln895_4_fu_900_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4) > unsigned(select_ln769_1_fu_880_p3)) else "0";
    icmp_ln895_5_fu_906_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4) > unsigned(ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4)) else "0";
    icmp_ln895_6_fu_912_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4) > unsigned(ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4)) else "0";
    icmp_ln895_7_fu_918_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4) > unsigned(select_ln769_fu_873_p3)) else "0";
    icmp_ln895_8_fu_924_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4) > unsigned(ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4)) else "0";
    icmp_ln895_9_fu_930_p2 <= "1" when (unsigned(ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4) > unsigned(ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4)) else "0";
    icmp_ln895_fu_653_p2 <= "1" when (signed(zext_ln887_2_fu_639_p1) > signed(sext_ln758_reg_1183)) else "0";
    init_buf_1_fu_574_p2 <= std_logic_vector(unsigned(i_op_assign_1_reg_298) + unsigned(ap_const_lv32_1));
    init_buf_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_ind_2_V_3_fu_110),32));
    init_row_ind_fu_485_p2 <= std_logic_vector(unsigned(i_op_assign_reg_265) + unsigned(ap_const_lv2_1));

    p_dst_data_V_blk_n_assign_proc : process(p_dst_data_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln850_reg_1120, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln630_reg_1233, and_ln636_reg_1249)
    begin
        if ((((ap_const_lv1_1 = and_ln636_reg_1249) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln630_reg_1233 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((icmp_ln850_reg_1120 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_dst_data_V_blk_n <= p_dst_data_V_empty_n;
        else 
            p_dst_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_dst_data_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln850_reg_1120, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_predicate_op169_read_state11, ap_block_pp1_stage0_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op169_read_state11 = ap_const_boolean_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((icmp_ln850_reg_1120 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            p_dst_data_V_read <= ap_const_logic_1;
        else 
            p_dst_data_V_read <= ap_const_logic_0;
        end if; 
    end process;


    p_dst_mat_data_V_blk_n_assign_proc : process(p_dst_mat_data_V_full_n, ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, icmp_ln891_reg_1268_pp1_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln891_reg_1268_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1))) then 
            p_dst_mat_data_V_blk_n <= p_dst_mat_data_V_full_n;
        else 
            p_dst_mat_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_mat_data_V_din <= (and_ln883_6_reg_1310 and and_ln883_2_fu_1001_p2);

    p_dst_mat_data_V_write_assign_proc : process(ap_enable_reg_pp1_iter4, icmp_ln891_reg_1268_pp1_iter3_reg, ap_block_pp1_stage0_11001)
    begin
        if (((icmp_ln891_reg_1268_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
            p_dst_mat_data_V_write <= ap_const_logic_1;
        else 
            p_dst_mat_data_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_image_height_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_image_height_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_image_height_blk_n <= p_image_height_empty_n;
        else 
            p_image_height_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_image_height_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_image_height_empty_n, p_image_width_empty_n)
    begin
        if ((not(((p_image_width_empty_n = ap_const_logic_0) or (p_image_height_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_image_height_read <= ap_const_logic_1;
        else 
            p_image_height_read <= ap_const_logic_0;
        end if; 
    end process;


    p_image_width_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_image_width_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_image_width_blk_n <= p_image_width_empty_n;
        else 
            p_image_width_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_image_width_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_image_height_empty_n, p_image_width_empty_n)
    begin
        if ((not(((p_image_width_empty_n = ap_const_logic_0) or (p_image_height_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_image_width_read <= ap_const_logic_1;
        else 
            p_image_width_read <= ap_const_logic_0;
        end if; 
    end process;

    readind_val_fu_561_p2 <= std_logic_vector(unsigned(index_assign_reg_308) + unsigned(ap_const_lv32_1));
    ret_V_1_fu_663_p2 <= std_logic_vector(unsigned(ap_const_lv14_2) - unsigned(ret_V_fu_658_p2));
    ret_V_fu_658_p2 <= std_logic_vector(unsigned(zext_ln887_2_fu_639_p1) - unsigned(sext_ln758_reg_1183));
    row_V_fu_1013_p2 <= std_logic_vector(unsigned(t_V_2_reg_374) + unsigned(ap_const_lv13_1));
    row_ind_0_V_2_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_op_assign_reg_265),13));
    select_ln769_1_fu_880_p3 <= 
        buf_cop_1_V_fu_836_p3 when (icmp_ln887_2_reg_1242_pp1_iter2_reg(0) = '1') else 
        ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4;
    select_ln769_2_fu_887_p3 <= 
        buf_cop_2_V_fu_866_p3 when (icmp_ln887_2_reg_1242_pp1_iter2_reg(0) = '1') else 
        ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4;
    select_ln769_fu_873_p3 <= 
        buf_cop_0_V_fu_806_p3 when (icmp_ln887_2_reg_1242_pp1_iter2_reg(0) = '1') else 
        ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4;
    select_ln791_1_fu_979_p3 <= 
        select_ln769_1_fu_880_p3 when (icmp_ln891_reg_1268(0) = '1') else 
        ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4;
    select_ln791_2_fu_986_p3 <= 
        select_ln769_2_fu_887_p3 when (icmp_ln891_reg_1268(0) = '1') else 
        ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4;
    select_ln791_fu_972_p3 <= 
        select_ln769_fu_873_p3 when (icmp_ln891_reg_1268(0) = '1') else 
        ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4;
        sext_ln758_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln758_fu_617_p2),14));

    tmp_fu_677_p3 <= ret_V_1_fu_663_p2(12 downto 12);
    trunc_ln1354_fu_669_p1 <= ret_V_1_fu_663_p2(13 - 1 downto 0);
    trunc_ln321_1_fu_546_p1 <= row_ind_2_V_1_load_reg_1060(2 - 1 downto 0);
    trunc_ln321_2_fu_715_p1 <= row_ind_1_V_1_reg_341(2 - 1 downto 0);
    trunc_ln321_3_fu_719_p1 <= zero_ind_V_reg_362(2 - 1 downto 0);
    trunc_ln321_4_fu_723_p1 <= row_ind_0_V_reg_351(2 - 1 downto 0);
    trunc_ln321_5_fu_779_p1 <= tmp_2_fu_768_p5(2 - 1 downto 0);
    trunc_ln321_fu_542_p1 <= i_op_assign_1_reg_298(2 - 1 downto 0);
    trunc_ln544_fu_673_p1 <= ret_V_1_fu_663_p2(2 - 1 downto 0);
    zext_ln544_1_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_reg_330),64));
    zext_ln544_2_fu_748_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_3_reg_458),64));
    zext_ln544_3_fu_755_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_3_reg_458_pp1_iter1_reg),64));
    zext_ln544_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_1_reg_318),64));
    zext_ln850_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_image_width_read_reg_1048),32));
    zext_ln887_1_fu_525_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_image_width_read_reg_1048),13));
    zext_ln887_2_fu_639_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_2_reg_374),14));
    zext_ln887_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_ind_2_V_2_fu_106),32));
end behav;
