-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fast is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_mat_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_mat_rows_empty_n : IN STD_LOGIC;
    p_src_mat_rows_read : OUT STD_LOGIC;
    p_src_mat_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_mat_cols_empty_n : IN STD_LOGIC;
    p_src_mat_cols_read : OUT STD_LOGIC;
    p_src_mat_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_mat_data_V_empty_n : IN STD_LOGIC;
    p_src_mat_data_V_read : OUT STD_LOGIC;
    p_dst_mat_data_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_mat_data_V_full_n : IN STD_LOGIC;
    p_dst_mat_data_V_write : OUT STD_LOGIC;
    threshold_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    threshold_empty_n : IN STD_LOGIC;
    threshold_read : OUT STD_LOGIC );
end;


architecture behav of fast is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_mat_rows_blk_n : STD_LOGIC;
    signal p_src_mat_cols_blk_n : STD_LOGIC;
    signal threshold_blk_n : STD_LOGIC;
    signal trunc_ln68_fu_57_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln68_reg_72 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln946_fu_62_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln946_reg_77 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln946_1_fu_67_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln946_1_reg_82 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_xFFastCornerDetectio_fu_46_p_src_mat_data_V_read : STD_LOGIC;
    signal grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_din : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_write : STD_LOGIC;
    signal grp_xFFastCornerDetectio_fu_46_ap_start : STD_LOGIC;
    signal grp_xFFastCornerDetectio_fu_46_ap_done : STD_LOGIC;
    signal grp_xFFastCornerDetectio_fu_46_ap_ready : STD_LOGIC;
    signal grp_xFFastCornerDetectio_fu_46_ap_idle : STD_LOGIC;
    signal grp_xFFastCornerDetectio_fu_46_ap_continue : STD_LOGIC;
    signal grp_xFFastCornerDetectio_fu_46_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call11 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_sync_grp_xFFastCornerDetectio_fu_46_ap_ready : STD_LOGIC;
    signal ap_sync_grp_xFFastCornerDetectio_fu_46_ap_done : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_done : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component xFFastCornerDetectio IS
    port (
        p_src_mat_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_mat_data_V_empty_n : IN STD_LOGIC;
        p_src_mat_data_V_read : OUT STD_LOGIC;
        p_dst_mat_data_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_mat_data_V_full_n : IN STD_LOGIC;
        p_dst_mat_data_V_write : OUT STD_LOGIC;
        p_image_height : IN STD_LOGIC_VECTOR (15 downto 0);
        p_image_width : IN STD_LOGIC_VECTOR (15 downto 0);
        p_threshold : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        p_image_height_ap_vld : IN STD_LOGIC;
        p_image_width_ap_vld : IN STD_LOGIC;
        p_threshold_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    grp_xFFastCornerDetectio_fu_46 : component xFFastCornerDetectio
    port map (
        p_src_mat_data_V_dout => p_src_mat_data_V_dout,
        p_src_mat_data_V_empty_n => p_src_mat_data_V_empty_n,
        p_src_mat_data_V_read => grp_xFFastCornerDetectio_fu_46_p_src_mat_data_V_read,
        p_dst_mat_data_V_din => grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_din,
        p_dst_mat_data_V_full_n => p_dst_mat_data_V_full_n,
        p_dst_mat_data_V_write => grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_write,
        p_image_height => trunc_ln946_reg_77,
        p_image_width => trunc_ln946_1_reg_82,
        p_threshold => trunc_ln68_reg_72,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        p_image_height_ap_vld => ap_const_logic_1,
        p_image_width_ap_vld => ap_const_logic_1,
        p_threshold_ap_vld => ap_const_logic_1,
        ap_start => grp_xFFastCornerDetectio_fu_46_ap_start,
        ap_done => grp_xFFastCornerDetectio_fu_46_ap_done,
        ap_ready => grp_xFFastCornerDetectio_fu_46_ap_ready,
        ap_idle => grp_xFFastCornerDetectio_fu_46_ap_idle,
        ap_continue => grp_xFFastCornerDetectio_fu_46_ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_done <= ap_const_logic_0;
                elsif ((grp_xFFastCornerDetectio_fu_46_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_ready <= ap_const_logic_0;
                elsif ((grp_xFFastCornerDetectio_fu_46_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_xFFastCornerDetectio_fu_46_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFFastCornerDetectio_fu_46_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_sync_grp_xFFastCornerDetectio_fu_46_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((ap_start = ap_const_logic_0) or (threshold_empty_n = ap_const_logic_0) or (p_src_mat_cols_empty_n = ap_const_logic_0) or (p_src_mat_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    grp_xFFastCornerDetectio_fu_46_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFFastCornerDetectio_fu_46_ap_ready = ap_const_logic_1)) then 
                    grp_xFFastCornerDetectio_fu_46_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (threshold_empty_n = ap_const_logic_0) or (p_src_mat_cols_empty_n = ap_const_logic_0) or (p_src_mat_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                trunc_ln68_reg_72 <= trunc_ln68_fu_57_p1;
                trunc_ln946_1_reg_82 <= trunc_ln946_1_fu_67_p1;
                trunc_ln946_reg_77 <= trunc_ln946_fu_62_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, p_src_mat_rows_empty_n, p_src_mat_cols_empty_n, threshold_empty_n, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (threshold_empty_n = ap_const_logic_0) or (p_src_mat_cols_empty_n = ap_const_logic_0) or (p_src_mat_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, p_src_mat_rows_empty_n, p_src_mat_cols_empty_n, threshold_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (threshold_empty_n = ap_const_logic_0) or (p_src_mat_cols_empty_n = ap_const_logic_0) or (p_src_mat_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call11_assign_proc : process(ap_start, ap_done_reg, p_src_mat_rows_empty_n, p_src_mat_cols_empty_n, threshold_empty_n)
    begin
                ap_block_state1_ignore_call11 <= ((ap_start = ap_const_logic_0) or (threshold_empty_n = ap_const_logic_0) or (p_src_mat_cols_empty_n = ap_const_logic_0) or (p_src_mat_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(ap_sync_grp_xFFastCornerDetectio_fu_46_ap_ready, ap_sync_grp_xFFastCornerDetectio_fu_46_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((ap_sync_grp_xFFastCornerDetectio_fu_46_ap_ready and ap_sync_grp_xFFastCornerDetectio_fu_46_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_xFFastCornerDetectio_fu_46_ap_done <= (grp_xFFastCornerDetectio_fu_46_ap_done or ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_done);
    ap_sync_grp_xFFastCornerDetectio_fu_46_ap_ready <= (grp_xFFastCornerDetectio_fu_46_ap_ready or ap_sync_reg_grp_xFFastCornerDetectio_fu_46_ap_ready);

    grp_xFFastCornerDetectio_fu_46_ap_continue_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            grp_xFFastCornerDetectio_fu_46_ap_continue <= ap_const_logic_1;
        else 
            grp_xFFastCornerDetectio_fu_46_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_xFFastCornerDetectio_fu_46_ap_start <= grp_xFFastCornerDetectio_fu_46_ap_start_reg;
    p_dst_mat_data_V_din <= grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_din;

    p_dst_mat_data_V_write_assign_proc : process(grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            p_dst_mat_data_V_write <= grp_xFFastCornerDetectio_fu_46_p_dst_mat_data_V_write;
        else 
            p_dst_mat_data_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_mat_cols_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_mat_cols_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_mat_cols_blk_n <= p_src_mat_cols_empty_n;
        else 
            p_src_mat_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_mat_cols_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_mat_rows_empty_n, p_src_mat_cols_empty_n, threshold_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (threshold_empty_n = ap_const_logic_0) or (p_src_mat_cols_empty_n = ap_const_logic_0) or (p_src_mat_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_mat_cols_read <= ap_const_logic_1;
        else 
            p_src_mat_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    p_src_mat_data_V_read_assign_proc : process(grp_xFFastCornerDetectio_fu_46_p_src_mat_data_V_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            p_src_mat_data_V_read <= grp_xFFastCornerDetectio_fu_46_p_src_mat_data_V_read;
        else 
            p_src_mat_data_V_read <= ap_const_logic_0;
        end if; 
    end process;


    p_src_mat_rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_mat_rows_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_mat_rows_blk_n <= p_src_mat_rows_empty_n;
        else 
            p_src_mat_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_mat_rows_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_mat_rows_empty_n, p_src_mat_cols_empty_n, threshold_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (threshold_empty_n = ap_const_logic_0) or (p_src_mat_cols_empty_n = ap_const_logic_0) or (p_src_mat_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_mat_rows_read <= ap_const_logic_1;
        else 
            p_src_mat_rows_read <= ap_const_logic_0;
        end if; 
    end process;


    threshold_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, threshold_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            threshold_blk_n <= threshold_empty_n;
        else 
            threshold_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    threshold_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_mat_rows_empty_n, p_src_mat_cols_empty_n, threshold_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (threshold_empty_n = ap_const_logic_0) or (p_src_mat_cols_empty_n = ap_const_logic_0) or (p_src_mat_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            threshold_read <= ap_const_logic_1;
        else 
            threshold_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln68_fu_57_p1 <= threshold_dout(8 - 1 downto 0);
    trunc_ln946_1_fu_67_p1 <= p_src_mat_cols_dout(16 - 1 downto 0);
    trunc_ln946_fu_62_p1 <= p_src_mat_rows_dout(16 - 1 downto 0);
end behav;
