// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module axis2xfMat (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        src_TDATA,
        src_TVALID,
        src_TREADY,
        p_src_data_V_din,
        p_src_data_V_full_n,
        p_src_data_V_write,
        src_rows_cast1_loc_dout,
        src_rows_cast1_loc_empty_n,
        src_rows_cast1_loc_read,
        src_cols_cast2_loc_dout,
        src_cols_cast2_loc_empty_n,
        src_cols_cast2_loc_read,
        src_rows_cast1_loc_out_din,
        src_rows_cast1_loc_out_full_n,
        src_rows_cast1_loc_out_write,
        src_cols_cast2_loc_out_din,
        src_cols_cast2_loc_out_full_n,
        src_cols_cast2_loc_out_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] src_TDATA;
input   src_TVALID;
output   src_TREADY;
output  [7:0] p_src_data_V_din;
input   p_src_data_V_full_n;
output   p_src_data_V_write;
input  [11:0] src_rows_cast1_loc_dout;
input   src_rows_cast1_loc_empty_n;
output   src_rows_cast1_loc_read;
input  [11:0] src_cols_cast2_loc_dout;
input   src_cols_cast2_loc_empty_n;
output   src_cols_cast2_loc_read;
output  [11:0] src_rows_cast1_loc_out_din;
input   src_rows_cast1_loc_out_full_n;
output   src_rows_cast1_loc_out_write;
output  [11:0] src_cols_cast2_loc_out_din;
input   src_cols_cast2_loc_out_full_n;
output   src_cols_cast2_loc_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg src_TREADY;
reg p_src_data_V_write;
reg src_rows_cast1_loc_read;
reg src_cols_cast2_loc_read;
reg src_rows_cast1_loc_out_write;
reg src_cols_cast2_loc_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    src_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln10_fu_134_p2;
reg    p_src_data_V_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln10_reg_168;
reg    src_rows_cast1_loc_blk_n;
reg    src_cols_cast2_loc_blk_n;
reg    src_rows_cast1_loc_out_blk_n;
reg    src_cols_cast2_loc_out_blk_n;
reg   [11:0] j_0_i_i_reg_112;
reg   [11:0] src_rows_cast1_loc_r_reg_149;
reg    ap_block_state1;
reg   [11:0] src_cols_cast2_loc_r_reg_154;
wire   [0:0] icmp_ln9_fu_123_p2;
wire    ap_CS_fsm_state2;
wire   [11:0] i_fu_128_p2;
reg   [11:0] i_reg_163;
reg    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [11:0] j_fu_139_p2;
wire   [7:0] trunc_ln209_fu_145_p1;
reg   [7:0] trunc_ln209_reg_177;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [11:0] i_0_i_i_reg_101;
wire    ap_CS_fsm_state5;
reg    ap_block_pp0_stage0_01001;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_src_data_V_U_apdone_blk;
wire   [23:0] src_TDATA_int;
wire    src_TVALID_int;
reg    src_TREADY_int;
wire    regslice_both_src_data_V_U_ack_in;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

regslice_both #(
    .DataWidth( 24 ))
regslice_both_src_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(src_TDATA),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_data_V_U_ack_in),
    .data_out(src_TDATA_int),
    .vld_out(src_TVALID_int),
    .ack_out(src_TREADY_int),
    .apdone_blk(regslice_both_src_data_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln9_fu_123_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln9_fu_123_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((icmp_ln9_fu_123_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_0_i_i_reg_101 <= i_reg_163;
    end else if ((~((src_cols_cast2_loc_out_full_n == 1'b0) | (src_rows_cast1_loc_out_full_n == 1'b0) | (src_cols_cast2_loc_empty_n == 1'b0) | (src_rows_cast1_loc_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_i_reg_101 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln9_fu_123_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_i_i_reg_112 <= 12'd0;
    end else if (((icmp_ln10_fu_134_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_0_i_i_reg_112 <= j_fu_139_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_163 <= i_fu_128_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln10_reg_168 <= icmp_ln10_fu_134_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((src_cols_cast2_loc_out_full_n == 1'b0) | (src_rows_cast1_loc_out_full_n == 1'b0) | (src_cols_cast2_loc_empty_n == 1'b0) | (src_rows_cast1_loc_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_cast2_loc_r_reg_154 <= src_cols_cast2_loc_dout;
        src_rows_cast1_loc_r_reg_149 <= src_rows_cast1_loc_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_134_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln209_reg_177 <= trunc_ln209_fu_145_p1;
    end
end

always @ (*) begin
    if ((icmp_ln10_fu_134_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln9_fu_123_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln9_fu_123_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_168 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_V_blk_n = p_src_data_V_full_n;
    end else begin
        p_src_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_168 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_V_write = 1'b1;
    end else begin
        p_src_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_134_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_TDATA_blk_n = src_TVALID_int;
    end else begin
        src_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((src_TVALID == 1'b1) & (regslice_both_src_data_V_U_ack_in == 1'b1))) begin
        src_TREADY = 1'b1;
    end else begin
        src_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_134_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_TREADY_int = 1'b1;
    end else begin
        src_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_cast2_loc_blk_n = src_cols_cast2_loc_empty_n;
    end else begin
        src_cols_cast2_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_cast2_loc_out_blk_n = src_cols_cast2_loc_out_full_n;
    end else begin
        src_cols_cast2_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((src_cols_cast2_loc_out_full_n == 1'b0) | (src_rows_cast1_loc_out_full_n == 1'b0) | (src_cols_cast2_loc_empty_n == 1'b0) | (src_rows_cast1_loc_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_cast2_loc_out_write = 1'b1;
    end else begin
        src_cols_cast2_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_cols_cast2_loc_out_full_n == 1'b0) | (src_rows_cast1_loc_out_full_n == 1'b0) | (src_cols_cast2_loc_empty_n == 1'b0) | (src_rows_cast1_loc_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_cast2_loc_read = 1'b1;
    end else begin
        src_cols_cast2_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_cast1_loc_blk_n = src_rows_cast1_loc_empty_n;
    end else begin
        src_rows_cast1_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_cast1_loc_out_blk_n = src_rows_cast1_loc_out_full_n;
    end else begin
        src_rows_cast1_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((src_cols_cast2_loc_out_full_n == 1'b0) | (src_rows_cast1_loc_out_full_n == 1'b0) | (src_cols_cast2_loc_empty_n == 1'b0) | (src_rows_cast1_loc_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_cast1_loc_out_write = 1'b1;
    end else begin
        src_rows_cast1_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((src_cols_cast2_loc_out_full_n == 1'b0) | (src_rows_cast1_loc_out_full_n == 1'b0) | (src_cols_cast2_loc_empty_n == 1'b0) | (src_rows_cast1_loc_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_cast1_loc_read = 1'b1;
    end else begin
        src_rows_cast1_loc_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((src_cols_cast2_loc_out_full_n == 1'b0) | (src_rows_cast1_loc_out_full_n == 1'b0) | (src_cols_cast2_loc_empty_n == 1'b0) | (src_rows_cast1_loc_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln9_fu_123_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln10_fu_134_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln10_fu_134_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln10_reg_168 == 1'd0) & (p_src_data_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln10_fu_134_p2 == 1'd0) & (src_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln10_reg_168 == 1'd0) & (p_src_data_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln10_fu_134_p2 == 1'd0) & (src_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln10_reg_168 == 1'd0) & (p_src_data_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln10_fu_134_p2 == 1'd0) & (src_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((src_cols_cast2_loc_out_full_n == 1'b0) | (src_rows_cast1_loc_out_full_n == 1'b0) | (src_cols_cast2_loc_empty_n == 1'b0) | (src_rows_cast1_loc_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter0 = ((icmp_ln10_fu_134_p2 == 1'd0) & (src_TVALID_int == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((icmp_ln10_reg_168 == 1'd0) & (p_src_data_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign i_fu_128_p2 = (i_0_i_i_reg_101 + 12'd1);

assign icmp_ln10_fu_134_p2 = ((j_0_i_i_reg_112 == src_cols_cast2_loc_r_reg_154) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_123_p2 = ((i_0_i_i_reg_101 == src_rows_cast1_loc_r_reg_149) ? 1'b1 : 1'b0);

assign j_fu_139_p2 = (j_0_i_i_reg_112 + 12'd1);

assign p_src_data_V_din = trunc_ln209_reg_177;

assign src_cols_cast2_loc_out_din = src_cols_cast2_loc_dout;

assign src_rows_cast1_loc_out_din = src_rows_cast1_loc_dout;

assign start_out = real_start;

assign trunc_ln209_fu_145_p1 = src_TDATA_int[7:0];

endmodule //axis2xfMat
