// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xFfastnms5781 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_dst_data_V_dout,
        p_dst_data_V_empty_n,
        p_dst_data_V_read,
        p_dst_mat_data_V_din,
        p_dst_mat_data_V_full_n,
        p_dst_mat_data_V_write,
        p_image_height_dout,
        p_image_height_empty_n,
        p_image_height_read,
        p_image_width_dout,
        p_image_width_empty_n,
        p_image_width_read
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_pp0_stage0 = 10'd8;
parameter    ap_ST_fsm_state6 = 10'd16;
parameter    ap_ST_fsm_state7 = 10'd32;
parameter    ap_ST_fsm_state8 = 10'd64;
parameter    ap_ST_fsm_state9 = 10'd128;
parameter    ap_ST_fsm_pp1_stage0 = 10'd256;
parameter    ap_ST_fsm_state15 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_dst_data_V_dout;
input   p_dst_data_V_empty_n;
output   p_dst_data_V_read;
output  [0:0] p_dst_mat_data_V_din;
input   p_dst_mat_data_V_full_n;
output   p_dst_mat_data_V_write;
input  [11:0] p_image_height_dout;
input   p_image_height_empty_n;
output   p_image_height_read;
input  [11:0] p_image_width_dout;
input   p_image_width_empty_n;
output   p_image_width_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_dst_data_V_read;
reg p_dst_mat_data_V_write;
reg p_image_height_read;
reg p_image_width_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_dst_data_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln850_reg_1120;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] icmp_ln630_reg_1233;
reg   [0:0] and_ln636_reg_1249;
reg    p_dst_mat_data_V_blk_n;
reg    ap_enable_reg_pp1_iter4;
reg   [0:0] icmp_ln891_reg_1268;
reg   [0:0] icmp_ln891_reg_1268_pp1_iter3_reg;
reg    p_image_height_blk_n;
reg    p_image_width_blk_n;
reg   [31:0] index_assign_reg_308;
reg   [11:0] t_V_1_reg_318;
reg   [7:0] src_buf_1_1_0_i_i_reg_386;
reg   [7:0] src_buf_1_0_0_i_i_reg_398;
reg   [7:0] src_buf_0_1_0_i_i_reg_410;
reg   [7:0] src_buf_0_0_0_i_i_reg_422;
reg   [7:0] src_buf_2_0_0_i_i_reg_434;
reg   [7:0] src_buf_2_1_0_i_i_reg_446;
reg   [12:0] t_V_3_reg_458;
reg   [12:0] t_V_3_reg_458_pp1_iter1_reg;
wire    ap_block_state10_pp1_stage0_iter0;
reg    ap_predicate_op169_read_state11;
reg    ap_block_state11_pp1_stage0_iter1;
wire    ap_block_state12_pp1_stage0_iter2;
wire    ap_block_state13_pp1_stage0_iter3;
reg    ap_block_state14_pp1_stage0_iter4;
reg    ap_block_pp1_stage0_11001;
reg   [11:0] p_image_height_read_reg_1043;
reg    ap_block_state1;
reg   [11:0] p_image_width_read_reg_1048;
reg   [12:0] row_ind_2_V_load_reg_1055;
wire    ap_CS_fsm_state2;
reg   [12:0] row_ind_2_V_1_load_reg_1060;
reg   [12:0] row_ind_2_V_2_load_reg_1066;
wire   [1:0] init_row_ind_fu_485_p2;
wire   [31:0] init_buf_fu_518_p1;
wire   [0:0] icmp_ln836_fu_479_p2;
wire   [31:0] zext_ln850_fu_522_p1;
reg   [31:0] zext_ln850_reg_1084;
wire   [12:0] zext_ln887_1_fu_525_p1;
reg   [12:0] zext_ln887_1_reg_1091;
wire   [31:0] zext_ln887_fu_528_p1;
reg   [31:0] zext_ln887_reg_1097;
wire   [0:0] icmp_ln887_fu_532_p2;
wire    ap_CS_fsm_state3;
wire   [31:0] add_ln856_fu_537_p2;
reg   [31:0] add_ln856_reg_1106;
wire   [1:0] trunc_ln321_fu_542_p1;
reg   [1:0] trunc_ln321_reg_1111;
wire   [1:0] trunc_ln321_1_fu_546_p1;
reg   [1:0] trunc_ln321_1_reg_1115;
wire   [0:0] icmp_ln850_fu_549_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [11:0] col_V_1_fu_555_p2;
reg   [11:0] col_V_1_reg_1124;
reg    ap_enable_reg_pp0_iter0;
wire   [31:0] readind_val_fu_561_p2;
wire   [31:0] init_buf_1_fu_574_p2;
wire    ap_CS_fsm_state6;
wire   [31:0] add_ln846_fu_580_p2;
wire   [11:0] col_V_fu_590_p2;
reg   [11:0] col_V_reg_1147;
wire    ap_CS_fsm_state7;
reg   [11:0] buf_0_V_addr_1_reg_1152;
wire   [0:0] icmp_ln861_fu_585_p2;
wire   [12:0] add_ln875_fu_603_p2;
reg   [12:0] add_ln875_reg_1168;
wire   [12:0] empty_12_fu_608_p1;
reg   [12:0] empty_12_reg_1173;
wire   [12:0] add_ln875_1_fu_611_p2;
reg   [12:0] add_ln875_1_reg_1178;
wire  signed [13:0] sext_ln758_fu_623_p1;
reg  signed [13:0] sext_ln758_reg_1183;
wire   [0:0] icmp_ln875_fu_643_p2;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln887_1_fu_648_p2;
reg   [0:0] icmp_ln887_1_reg_1193;
wire   [1:0] trunc_ln544_fu_673_p1;
reg   [1:0] trunc_ln544_reg_1198;
wire   [0:0] and_ln758_fu_685_p2;
reg   [0:0] and_ln758_reg_1203;
wire   [0:0] and_ln758_1_fu_697_p2;
reg   [0:0] and_ln758_1_reg_1208;
wire   [0:0] and_ln758_2_fu_709_p2;
reg   [0:0] and_ln758_2_reg_1213;
wire   [1:0] trunc_ln321_2_fu_715_p1;
reg   [1:0] trunc_ln321_2_reg_1218;
wire   [1:0] trunc_ln321_3_fu_719_p1;
reg   [1:0] trunc_ln321_3_reg_1223;
wire   [1:0] trunc_ln321_4_fu_723_p1;
reg   [1:0] trunc_ln321_4_reg_1228;
wire   [0:0] icmp_ln630_fu_727_p2;
reg   [0:0] icmp_ln630_reg_1233_pp1_iter1_reg;
reg   [0:0] icmp_ln630_reg_1233_pp1_iter2_reg;
reg   [0:0] icmp_ln630_reg_1233_pp1_iter3_reg;
wire   [12:0] col_V_2_fu_732_p2;
reg   [12:0] col_V_2_reg_1237;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] icmp_ln887_2_fu_738_p2;
reg   [0:0] icmp_ln887_2_reg_1242;
reg   [0:0] icmp_ln887_2_reg_1242_pp1_iter1_reg;
reg   [0:0] icmp_ln887_2_reg_1242_pp1_iter2_reg;
wire   [0:0] and_ln636_fu_743_p2;
wire   [0:0] icmp_ln891_fu_762_p2;
wire   [7:0] select_ln769_fu_873_p3;
reg   [7:0] select_ln769_reg_1275;
reg    ap_enable_reg_pp1_iter3;
wire   [7:0] select_ln769_1_fu_880_p3;
reg   [7:0] select_ln769_1_reg_1280;
wire   [7:0] select_ln769_2_fu_887_p3;
reg   [7:0] select_ln769_2_reg_1285;
wire   [0:0] icmp_ln895_3_fu_894_p2;
reg   [0:0] icmp_ln895_3_reg_1290;
wire   [0:0] icmp_ln895_4_fu_900_p2;
reg   [0:0] icmp_ln895_4_reg_1295;
wire   [0:0] icmp_ln895_5_fu_906_p2;
reg   [0:0] icmp_ln895_5_reg_1300;
wire   [0:0] icmp_ln895_6_fu_912_p2;
reg   [0:0] icmp_ln895_6_reg_1305;
wire   [0:0] and_ln883_6_fu_966_p2;
reg   [0:0] and_ln883_6_reg_1310;
wire   [7:0] select_ln791_fu_972_p3;
reg   [7:0] select_ln791_reg_1315;
wire   [7:0] select_ln791_1_fu_979_p3;
reg   [7:0] select_ln791_1_reg_1320;
wire   [7:0] select_ln791_2_fu_986_p3;
reg   [7:0] select_ln791_2_reg_1325;
wire   [12:0] row_V_fu_1013_p2;
wire    ap_CS_fsm_state15;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state10;
reg    ap_enable_reg_pp1_iter2;
reg   [11:0] buf_0_V_address0;
reg    buf_0_V_ce0;
wire   [7:0] buf_0_V_q0;
reg   [11:0] buf_0_V_address1;
reg    buf_0_V_ce1;
reg    buf_0_V_we1;
reg   [7:0] buf_0_V_d1;
reg   [11:0] buf_1_V_address0;
reg    buf_1_V_ce0;
wire   [7:0] buf_1_V_q0;
reg   [11:0] buf_1_V_address1;
reg    buf_1_V_ce1;
reg    buf_1_V_we1;
reg   [11:0] buf_2_V_address0;
reg    buf_2_V_ce0;
wire   [7:0] buf_2_V_q0;
reg   [11:0] buf_2_V_address1;
reg    buf_2_V_ce1;
reg    buf_2_V_we1;
wire   [1:0] ap_phi_mux_i_op_assign_phi_fu_269_p4;
reg   [1:0] i_op_assign_reg_265;
reg   [31:0] indvars_iv_i_i_reg_276;
reg   [31:0] readind_val_0_i_i_reg_286;
reg   [31:0] i_op_assign_1_reg_298;
reg   [11:0] ap_phi_mux_t_V_1_phi_fu_322_p4;
reg   [11:0] t_V_reg_330;
wire    ap_CS_fsm_state8;
reg   [12:0] row_ind_1_V_1_reg_341;
reg   [12:0] zero_ind_V_reg_362;
reg   [12:0] row_ind_0_V_reg_351;
reg   [12:0] t_V_2_reg_374;
reg   [7:0] ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4;
reg   [7:0] ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4;
reg   [7:0] ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4;
reg   [7:0] ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4;
reg   [7:0] ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4;
reg   [7:0] ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4;
reg   [12:0] ap_phi_mux_t_V_3_phi_fu_462_p4;
wire   [63:0] zext_ln544_fu_567_p1;
wire   [63:0] zext_ln544_1_fu_596_p1;
wire   [63:0] zext_ln544_2_fu_748_p1;
wire   [63:0] zext_ln544_3_fu_755_p1;
reg   [12:0] row_ind_2_V_fu_98;
wire   [12:0] row_ind_0_V_2_fu_491_p1;
reg   [12:0] row_ind_2_V_1_fu_102;
reg   [12:0] row_ind_2_V_2_fu_106;
reg   [12:0] row_ind_2_V_3_fu_110;
reg    ap_block_pp1_stage0_01001;
wire   [7:0] tmp_1_fu_627_p5;
wire   [12:0] add_ln758_fu_617_p2;
wire   [13:0] zext_ln887_2_fu_639_p1;
wire   [13:0] ret_V_fu_658_p2;
wire   [13:0] ret_V_1_fu_663_p2;
wire   [0:0] icmp_ln895_fu_653_p2;
wire   [0:0] tmp_fu_677_p3;
wire   [12:0] trunc_ln1354_fu_669_p1;
wire   [0:0] icmp_ln895_1_fu_691_p2;
wire   [0:0] icmp_ln895_2_fu_703_p2;
wire   [12:0] tmp_2_fu_768_p5;
wire   [1:0] trunc_ln321_5_fu_779_p1;
wire   [7:0] tmp_3_fu_783_p5;
wire   [7:0] tmp_4_fu_795_p5;
wire   [7:0] tmp_5_fu_813_p5;
wire   [7:0] tmp_6_fu_825_p5;
wire   [7:0] tmp_7_fu_843_p5;
wire   [7:0] tmp_8_fu_855_p5;
wire   [7:0] buf_cop_0_V_fu_806_p3;
wire   [7:0] buf_cop_1_V_fu_836_p3;
wire   [7:0] buf_cop_2_V_fu_866_p3;
wire   [0:0] icmp_ln895_7_fu_918_p2;
wire   [0:0] icmp_ln895_8_fu_924_p2;
wire   [0:0] icmp_ln895_10_fu_936_p2;
wire   [0:0] icmp_ln883_fu_942_p2;
wire   [0:0] and_ln883_4_fu_954_p2;
wire   [0:0] icmp_ln895_9_fu_930_p2;
wire   [0:0] and_ln883_5_fu_960_p2;
wire   [0:0] and_ln883_3_fu_948_p2;
wire   [0:0] and_ln883_1_fu_997_p2;
wire   [0:0] and_ln883_fu_993_p2;
wire   [0:0] and_ln883_2_fu_1001_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
end

xFfast7x75682_bufbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
buf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_0_V_address0),
    .ce0(buf_0_V_ce0),
    .q0(buf_0_V_q0),
    .address1(buf_0_V_address1),
    .ce1(buf_0_V_ce1),
    .we1(buf_0_V_we1),
    .d1(buf_0_V_d1)
);

xFfast7x75682_bufbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
buf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_1_V_address0),
    .ce0(buf_1_V_ce0),
    .q0(buf_1_V_q0),
    .address1(buf_1_V_address1),
    .ce1(buf_1_V_ce1),
    .we1(buf_1_V_we1),
    .d1(p_dst_data_V_dout)
);

xFfast7x75682_bufbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
buf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2_V_address0),
    .ce0(buf_2_V_ce0),
    .q0(buf_2_V_q0),
    .address1(buf_2_V_address1),
    .ce1(buf_2_V_ce1),
    .we1(buf_2_V_we1),
    .d1(p_dst_data_V_dout)
);

fast_accel_mux_32ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fast_accel_mux_32ncg_U41(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(trunc_ln321_1_reg_1115),
    .dout(tmp_1_fu_627_p5)
);

fast_accel_mux_32ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 13 ))
fast_accel_mux_32ocq_U42(
    .din0(zero_ind_V_reg_362),
    .din1(row_ind_0_V_reg_351),
    .din2(row_ind_1_V_1_reg_341),
    .din3(trunc_ln544_reg_1198),
    .dout(tmp_2_fu_768_p5)
);

fast_accel_mux_32ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fast_accel_mux_32ncg_U43(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(trunc_ln321_5_fu_779_p1),
    .dout(tmp_3_fu_783_p5)
);

fast_accel_mux_32ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fast_accel_mux_32ncg_U44(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(trunc_ln321_3_reg_1223),
    .dout(tmp_4_fu_795_p5)
);

fast_accel_mux_32ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fast_accel_mux_32ncg_U45(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(trunc_ln321_5_fu_779_p1),
    .dout(tmp_5_fu_813_p5)
);

fast_accel_mux_32ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fast_accel_mux_32ncg_U46(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(trunc_ln321_4_reg_1228),
    .dout(tmp_6_fu_825_p5)
);

fast_accel_mux_32ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fast_accel_mux_32ncg_U47(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(trunc_ln321_5_fu_779_p1),
    .dout(tmp_7_fu_843_p5)
);

fast_accel_mux_32ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fast_accel_mux_32ncg_U48(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(trunc_ln321_2_reg_1218),
    .dout(tmp_8_fu_855_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln875_fu_643_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln887_fu_532_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((icmp_ln887_fu_532_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state10))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state10)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state10);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_enable_reg_pp1_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_op_assign_1_reg_298 <= init_buf_fu_518_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_op_assign_1_reg_298 <= init_buf_1_fu_574_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_479_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_op_assign_reg_265 <= init_row_ind_fu_485_p2;
    end else if ((~((p_image_width_empty_n == 1'b0) | (p_image_height_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_op_assign_reg_265 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln850_fu_549_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        index_assign_reg_308 <= readind_val_fu_561_p2;
    end else if (((icmp_ln887_fu_532_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        index_assign_reg_308 <= readind_val_0_i_i_reg_286;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        indvars_iv_i_i_reg_276 <= zext_ln850_fu_522_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indvars_iv_i_i_reg_276 <= add_ln846_fu_580_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        readind_val_0_i_i_reg_286 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        readind_val_0_i_i_reg_286 <= add_ln856_reg_1106;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        row_ind_0_V_reg_351 <= row_ind_1_V_1_reg_341;
    end else if (((icmp_ln861_fu_585_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        row_ind_0_V_reg_351 <= row_ind_2_V_1_load_reg_1060;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        row_ind_1_V_1_reg_341 <= zero_ind_V_reg_362;
    end else if (((icmp_ln861_fu_585_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        row_ind_1_V_1_reg_341 <= row_ind_2_V_2_load_reg_1066;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf_0_0_0_i_i_reg_422 <= select_ln791_reg_1315;
    end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_0_0_0_i_i_reg_422 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf_0_1_0_i_i_reg_410 <= select_ln769_reg_1275;
    end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_0_1_0_i_i_reg_410 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf_1_0_0_i_i_reg_398 <= select_ln791_1_reg_1320;
    end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_1_0_0_i_i_reg_398 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf_1_1_0_i_i_reg_386 <= select_ln769_1_reg_1280;
    end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_1_1_0_i_i_reg_386 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf_2_0_0_i_i_reg_434 <= select_ln791_2_reg_1325;
    end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_2_0_0_i_i_reg_434 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf_2_1_0_i_i_reg_446 <= select_ln769_2_reg_1285;
    end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_2_1_0_i_i_reg_446 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln850_reg_1120 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_1_reg_318 <= col_V_1_reg_1124;
    end else if (((icmp_ln887_fu_532_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_1_reg_318 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        t_V_2_reg_374 <= row_V_fu_1013_p2;
    end else if (((icmp_ln861_fu_585_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        t_V_2_reg_374 <= 13'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        t_V_3_reg_458 <= col_V_2_reg_1237;
    end else if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        t_V_3_reg_458 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln887_fu_532_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_reg_330 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        t_V_reg_330 <= col_V_reg_1147;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        zero_ind_V_reg_362 <= row_ind_0_V_reg_351;
    end else if (((icmp_ln861_fu_585_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        zero_ind_V_reg_362 <= row_ind_2_V_load_reg_1055;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln887_fu_532_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln856_reg_1106 <= add_ln856_fu_537_p2;
        trunc_ln321_reg_1111 <= trunc_ln321_fu_542_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln861_fu_585_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        add_ln875_1_reg_1178 <= add_ln875_1_fu_611_p2;
        add_ln875_reg_1168 <= add_ln875_fu_603_p2;
        empty_12_reg_1173[11 : 0] <= empty_12_fu_608_p1[11 : 0];
        sext_ln758_reg_1183 <= sext_ln758_fu_623_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_fu_727_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        and_ln636_reg_1249 <= and_ln636_fu_743_p2;
        icmp_ln887_2_reg_1242 <= icmp_ln887_2_fu_738_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln875_fu_643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        and_ln758_1_reg_1208 <= and_ln758_1_fu_697_p2;
        and_ln758_2_reg_1213 <= and_ln758_2_fu_709_p2;
        and_ln758_reg_1203 <= and_ln758_fu_685_p2;
        icmp_ln887_1_reg_1193 <= icmp_ln887_1_fu_648_p2;
        trunc_ln321_2_reg_1218 <= trunc_ln321_2_fu_715_p1;
        trunc_ln321_3_reg_1223 <= trunc_ln321_3_fu_719_p1;
        trunc_ln321_4_reg_1228 <= trunc_ln321_4_fu_723_p1;
        trunc_ln544_reg_1198 <= trunc_ln544_fu_673_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter2_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        and_ln883_6_reg_1310 <= and_ln883_6_fu_966_p2;
        icmp_ln895_3_reg_1290 <= icmp_ln895_3_fu_894_p2;
        icmp_ln895_4_reg_1295 <= icmp_ln895_4_fu_900_p2;
        icmp_ln895_5_reg_1300 <= icmp_ln895_5_fu_906_p2;
        icmp_ln895_6_reg_1305 <= icmp_ln895_6_fu_912_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln861_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_0_V_addr_1_reg_1152 <= zext_ln544_1_fu_596_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_V_1_reg_1124 <= col_V_1_fu_555_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        col_V_2_reg_1237 <= col_V_2_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        col_V_reg_1147 <= col_V_fu_590_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln630_reg_1233 <= icmp_ln630_fu_727_p2;
        icmp_ln630_reg_1233_pp1_iter1_reg <= icmp_ln630_reg_1233;
        icmp_ln887_2_reg_1242_pp1_iter1_reg <= icmp_ln887_2_reg_1242;
        t_V_3_reg_458_pp1_iter1_reg <= t_V_3_reg_458;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln630_reg_1233_pp1_iter2_reg <= icmp_ln630_reg_1233_pp1_iter1_reg;
        icmp_ln630_reg_1233_pp1_iter3_reg <= icmp_ln630_reg_1233_pp1_iter2_reg;
        icmp_ln887_2_reg_1242_pp1_iter2_reg <= icmp_ln887_2_reg_1242_pp1_iter1_reg;
        icmp_ln891_reg_1268_pp1_iter3_reg <= icmp_ln891_reg_1268;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln850_reg_1120 <= icmp_ln850_fu_549_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln891_reg_1268 <= icmp_ln891_fu_762_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_image_width_empty_n == 1'b0) | (p_image_height_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_height_read_reg_1043 <= p_image_height_dout;
        p_image_width_read_reg_1048 <= p_image_width_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_479_p2 == 1'd0) & (ap_phi_mux_i_op_assign_phi_fu_269_p4 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_2_V_1_fu_102[1 : 0] <= row_ind_0_V_2_fu_491_p1[1 : 0];
        row_ind_2_V_3_fu_110[1 : 0] <= row_ind_0_V_2_fu_491_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_ind_2_V_1_load_reg_1060[1 : 0] <= row_ind_2_V_1_fu_102[1 : 0];
        row_ind_2_V_2_load_reg_1066[1 : 0] <= row_ind_2_V_2_fu_106[1 : 0];
        row_ind_2_V_load_reg_1055[1 : 0] <= row_ind_2_V_fu_98[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_i_op_assign_phi_fu_269_p4 == 2'd1) & ~(ap_phi_mux_i_op_assign_phi_fu_269_p4 == 2'd0) & (icmp_ln836_fu_479_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_2_V_2_fu_106[1 : 0] <= row_ind_0_V_2_fu_491_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_479_p2 == 1'd0) & (ap_phi_mux_i_op_assign_phi_fu_269_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_2_V_fu_98[1 : 0] <= row_ind_0_V_2_fu_491_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln630_reg_1233_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        select_ln769_1_reg_1280 <= select_ln769_1_fu_880_p3;
        select_ln769_2_reg_1285 <= select_ln769_2_fu_887_p3;
        select_ln769_reg_1275 <= select_ln769_fu_873_p3;
        select_ln791_1_reg_1320 <= select_ln791_1_fu_979_p3;
        select_ln791_2_reg_1325 <= select_ln791_2_fu_986_p3;
        select_ln791_reg_1315 <= select_ln791_fu_972_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln887_fu_532_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        trunc_ln321_1_reg_1115 <= trunc_ln321_1_fu_546_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln850_reg_1084[11 : 0] <= zext_ln850_fu_522_p1[11 : 0];
        zext_ln887_1_reg_1091[11 : 0] <= zext_ln887_1_fu_525_p1[11 : 0];
        zext_ln887_reg_1097[1 : 0] <= zext_ln887_fu_528_p1[1 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln850_fu_549_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln630_fu_727_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state10 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state10 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln875_fu_643_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4 = select_ln791_reg_1315;
    end else begin
        ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4 = src_buf_0_0_0_i_i_reg_422;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4 = select_ln769_reg_1275;
    end else begin
        ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4 = src_buf_0_1_0_i_i_reg_410;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4 = select_ln791_1_reg_1320;
    end else begin
        ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4 = src_buf_1_0_0_i_i_reg_398;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 = select_ln769_1_reg_1280;
    end else begin
        ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 = src_buf_1_1_0_i_i_reg_386;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4 = select_ln791_2_reg_1325;
    end else begin
        ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4 = src_buf_2_0_0_i_i_reg_434;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln630_reg_1233_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4 = select_ln769_2_reg_1285;
    end else begin
        ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4 = src_buf_2_1_0_i_i_reg_446;
    end
end

always @ (*) begin
    if (((icmp_ln850_reg_1120 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_t_V_1_phi_fu_322_p4 = col_V_1_reg_1124;
    end else begin
        ap_phi_mux_t_V_1_phi_fu_322_p4 = t_V_1_reg_318;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln630_reg_1233 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_t_V_3_phi_fu_462_p4 = col_V_2_reg_1237;
    end else begin
        ap_phi_mux_t_V_3_phi_fu_462_p4 = t_V_3_reg_458;
    end
end

always @ (*) begin
    if (((icmp_ln875_fu_643_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        buf_0_V_address0 = zext_ln544_3_fu_755_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_0_V_address0 = zext_ln544_1_fu_596_p1;
    end else begin
        buf_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buf_0_V_address1 = zext_ln544_2_fu_748_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_0_V_address1 = buf_0_V_addr_1_reg_1152;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_0_V_address1 = zext_ln544_fu_567_p1;
    end else begin
        buf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        buf_0_V_ce0 = 1'b1;
    end else begin
        buf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_0_V_ce1 = 1'b1;
    end else begin
        buf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_0_V_d1 = tmp_1_fu_627_p5;
    end else if ((((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_0_V_d1 = p_dst_data_V_dout;
    end else begin
        buf_0_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'd1 == and_ln636_reg_1249) & (icmp_ln630_reg_1233 == 1'd0) & (trunc_ln321_2_reg_1218 == 2'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln321_reg_1111 == 2'd0)))) begin
        buf_0_V_we1 = 1'b1;
    end else begin
        buf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        buf_1_V_address0 = zext_ln544_3_fu_755_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_1_V_address0 = zext_ln544_1_fu_596_p1;
    end else begin
        buf_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buf_1_V_address1 = zext_ln544_2_fu_748_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_1_V_address1 = zext_ln544_fu_567_p1;
    end else begin
        buf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        buf_1_V_ce0 = 1'b1;
    end else begin
        buf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_1_V_ce1 = 1'b1;
    end else begin
        buf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln636_reg_1249) & (icmp_ln630_reg_1233 == 1'd0) & (trunc_ln321_2_reg_1218 == 2'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln321_reg_1111 == 2'd1)))) begin
        buf_1_V_we1 = 1'b1;
    end else begin
        buf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        buf_2_V_address0 = zext_ln544_3_fu_755_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_2_V_address0 = zext_ln544_1_fu_596_p1;
    end else begin
        buf_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buf_2_V_address1 = zext_ln544_2_fu_748_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2_V_address1 = zext_ln544_fu_567_p1;
    end else begin
        buf_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        buf_2_V_ce0 = 1'b1;
    end else begin
        buf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_2_V_ce1 = 1'b1;
    end else begin
        buf_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~(trunc_ln321_2_reg_1218 == 2'd0) & ~(trunc_ln321_2_reg_1218 == 2'd1) & (1'd1 == and_ln636_reg_1249) & (icmp_ln630_reg_1233 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | (~(trunc_ln321_reg_1111 == 2'd0) & ~(trunc_ln321_reg_1111 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_2_V_we1 = 1'b1;
    end else begin
        buf_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln636_reg_1249) & (1'b0 == ap_block_pp1_stage0) & (icmp_ln630_reg_1233 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((icmp_ln850_reg_1120 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_dst_data_V_blk_n = p_dst_data_V_empty_n;
    end else begin
        p_dst_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op169_read_state11 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((icmp_ln850_reg_1120 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_dst_data_V_read = 1'b1;
    end else begin
        p_dst_data_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln891_reg_1268_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        p_dst_mat_data_V_blk_n = p_dst_mat_data_V_full_n;
    end else begin
        p_dst_mat_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1268_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_dst_mat_data_V_write = 1'b1;
    end else begin
        p_dst_mat_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_height_blk_n = p_image_height_empty_n;
    end else begin
        p_image_height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_image_width_empty_n == 1'b0) | (p_image_height_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_height_read = 1'b1;
    end else begin
        p_image_height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_width_blk_n = p_image_width_empty_n;
    end else begin
        p_image_width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_image_width_empty_n == 1'b0) | (p_image_height_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_width_read = 1'b1;
    end else begin
        p_image_width_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((p_image_width_empty_n == 1'b0) | (p_image_height_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln836_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln887_fu_532_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln850_fu_549_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln850_fu_549_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln861_fu_585_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln875_fu_643_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((icmp_ln630_fu_727_p2 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b1)) | ((icmp_ln630_fu_727_p2 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln758_fu_617_p2 = ($signed(empty_12_fu_608_p1) + $signed(13'd8191));

assign add_ln846_fu_580_p2 = (zext_ln850_reg_1084 + indvars_iv_i_i_reg_276);

assign add_ln856_fu_537_p2 = (zext_ln850_reg_1084 + readind_val_0_i_i_reg_286);

assign add_ln875_1_fu_611_p2 = (empty_12_fu_608_p1 + 13'd1);

assign add_ln875_fu_603_p2 = (zext_ln887_1_reg_1091 + 13'd1);

assign and_ln636_fu_743_p2 = (icmp_ln887_2_fu_738_p2 & icmp_ln887_1_reg_1193);

assign and_ln758_1_fu_697_p2 = (icmp_ln895_fu_653_p2 & icmp_ln895_1_fu_691_p2);

assign and_ln758_2_fu_709_p2 = (icmp_ln895_fu_653_p2 & icmp_ln895_2_fu_703_p2);

assign and_ln758_fu_685_p2 = (tmp_fu_677_p3 & icmp_ln895_fu_653_p2);

assign and_ln883_1_fu_997_p2 = (icmp_ln895_6_reg_1305 & icmp_ln895_5_reg_1300);

assign and_ln883_2_fu_1001_p2 = (and_ln883_fu_993_p2 & and_ln883_1_fu_997_p2);

assign and_ln883_3_fu_948_p2 = (icmp_ln895_8_fu_924_p2 & icmp_ln895_7_fu_918_p2);

assign and_ln883_4_fu_954_p2 = (icmp_ln895_10_fu_936_p2 & icmp_ln883_fu_942_p2);

assign and_ln883_5_fu_960_p2 = (icmp_ln895_9_fu_930_p2 & and_ln883_4_fu_954_p2);

assign and_ln883_6_fu_966_p2 = (and_ln883_5_fu_960_p2 & and_ln883_3_fu_948_p2);

assign and_ln883_fu_993_p2 = (icmp_ln895_4_reg_1295 & icmp_ln895_3_reg_1290);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln850_reg_1120 == 1'd0) & (p_dst_data_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln850_reg_1120 == 1'd0) & (p_dst_data_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((icmp_ln891_reg_1268_pp1_iter3_reg == 1'd0) & (p_dst_mat_data_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b1)) | ((p_dst_data_V_empty_n == 1'b0) & (ap_predicate_op169_read_state11 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((icmp_ln891_reg_1268_pp1_iter3_reg == 1'd0) & (p_dst_mat_data_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b1)) | ((p_dst_data_V_empty_n == 1'b0) & (ap_predicate_op169_read_state11 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((icmp_ln891_reg_1268_pp1_iter3_reg == 1'd0) & (p_dst_mat_data_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b1)) | ((p_dst_data_V_empty_n == 1'b0) & (ap_predicate_op169_read_state11 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((p_image_width_empty_n == 1'b0) | (p_image_height_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp1_stage0_iter1 = ((p_dst_data_V_empty_n == 1'b0) & (ap_predicate_op169_read_state11 == 1'b1));
end

assign ap_block_state12_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp1_stage0_iter4 = ((icmp_ln891_reg_1268_pp1_iter3_reg == 1'd0) & (p_dst_mat_data_V_full_n == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((icmp_ln850_reg_1120 == 1'd0) & (p_dst_data_V_empty_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_mux_i_op_assign_phi_fu_269_p4 = i_op_assign_reg_265;

always @ (*) begin
    ap_predicate_op169_read_state11 = ((1'd1 == and_ln636_reg_1249) & (icmp_ln630_reg_1233 == 1'd0));
end

assign buf_cop_0_V_fu_806_p3 = ((and_ln758_reg_1203[0:0] === 1'b1) ? tmp_3_fu_783_p5 : tmp_4_fu_795_p5);

assign buf_cop_1_V_fu_836_p3 = ((and_ln758_1_reg_1208[0:0] === 1'b1) ? tmp_5_fu_813_p5 : tmp_6_fu_825_p5);

assign buf_cop_2_V_fu_866_p3 = ((and_ln758_2_reg_1213[0:0] === 1'b1) ? tmp_7_fu_843_p5 : tmp_8_fu_855_p5);

assign col_V_1_fu_555_p2 = (ap_phi_mux_t_V_1_phi_fu_322_p4 + 12'd1);

assign col_V_2_fu_732_p2 = (ap_phi_mux_t_V_3_phi_fu_462_p4 + 13'd1);

assign col_V_fu_590_p2 = (t_V_reg_330 + 12'd1);

assign empty_12_fu_608_p1 = p_image_height_read_reg_1043;

assign icmp_ln630_fu_727_p2 = ((ap_phi_mux_t_V_3_phi_fu_462_p4 == add_ln875_reg_1168) ? 1'b1 : 1'b0);

assign icmp_ln836_fu_479_p2 = ((i_op_assign_reg_265 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln850_fu_549_p2 = ((index_assign_reg_308 == indvars_iv_i_i_reg_276) ? 1'b1 : 1'b0);

assign icmp_ln861_fu_585_p2 = ((t_V_reg_330 == p_image_width_read_reg_1048) ? 1'b1 : 1'b0);

assign icmp_ln875_fu_643_p2 = ((t_V_2_reg_374 == add_ln875_1_reg_1178) ? 1'b1 : 1'b0);

assign icmp_ln883_fu_942_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln887_1_fu_648_p2 = ((t_V_2_reg_374 < empty_12_reg_1173) ? 1'b1 : 1'b0);

assign icmp_ln887_2_fu_738_p2 = ((ap_phi_mux_t_V_3_phi_fu_462_p4 < zext_ln887_1_reg_1091) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_532_p2 = (($signed(i_op_assign_1_reg_298) < $signed(zext_ln887_reg_1097)) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_762_p2 = ((t_V_3_reg_458_pp1_iter1_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_10_fu_936_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 > select_ln769_2_fu_887_p3) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_691_p2 = (($signed(trunc_ln1354_fu_669_p1) < $signed(13'd1)) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_703_p2 = (($signed(ret_V_fu_658_p2) > $signed(14'd0)) ? 1'b1 : 1'b0);

assign icmp_ln895_3_fu_894_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 > ap_phi_mux_src_buf_1_0_0_i_i_phi_fu_402_p4) ? 1'b1 : 1'b0);

assign icmp_ln895_4_fu_900_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 > select_ln769_1_fu_880_p3) ? 1'b1 : 1'b0);

assign icmp_ln895_5_fu_906_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 > ap_phi_mux_src_buf_0_0_0_i_i_phi_fu_426_p4) ? 1'b1 : 1'b0);

assign icmp_ln895_6_fu_912_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 > ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4) ? 1'b1 : 1'b0);

assign icmp_ln895_7_fu_918_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 > select_ln769_fu_873_p3) ? 1'b1 : 1'b0);

assign icmp_ln895_8_fu_924_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 > ap_phi_mux_src_buf_2_0_0_i_i_phi_fu_438_p4) ? 1'b1 : 1'b0);

assign icmp_ln895_9_fu_930_p2 = ((ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4 > ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_653_p2 = (($signed(zext_ln887_2_fu_639_p1) > $signed(sext_ln758_reg_1183)) ? 1'b1 : 1'b0);

assign init_buf_1_fu_574_p2 = (i_op_assign_1_reg_298 + 32'd1);

assign init_buf_fu_518_p1 = row_ind_2_V_3_fu_110;

assign init_row_ind_fu_485_p2 = (i_op_assign_reg_265 + 2'd1);

assign p_dst_mat_data_V_din = (and_ln883_6_reg_1310 & and_ln883_2_fu_1001_p2);

assign readind_val_fu_561_p2 = (index_assign_reg_308 + 32'd1);

assign ret_V_1_fu_663_p2 = (14'd2 - ret_V_fu_658_p2);

assign ret_V_fu_658_p2 = ($signed(zext_ln887_2_fu_639_p1) - $signed(sext_ln758_reg_1183));

assign row_V_fu_1013_p2 = (t_V_2_reg_374 + 13'd1);

assign row_ind_0_V_2_fu_491_p1 = i_op_assign_reg_265;

assign select_ln769_1_fu_880_p3 = ((icmp_ln887_2_reg_1242_pp1_iter2_reg[0:0] === 1'b1) ? buf_cop_1_V_fu_836_p3 : ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4);

assign select_ln769_2_fu_887_p3 = ((icmp_ln887_2_reg_1242_pp1_iter2_reg[0:0] === 1'b1) ? buf_cop_2_V_fu_866_p3 : ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4);

assign select_ln769_fu_873_p3 = ((icmp_ln887_2_reg_1242_pp1_iter2_reg[0:0] === 1'b1) ? buf_cop_0_V_fu_806_p3 : ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4);

assign select_ln791_1_fu_979_p3 = ((icmp_ln891_reg_1268[0:0] === 1'b1) ? select_ln769_1_fu_880_p3 : ap_phi_mux_src_buf_1_1_0_i_i_phi_fu_390_p4);

assign select_ln791_2_fu_986_p3 = ((icmp_ln891_reg_1268[0:0] === 1'b1) ? select_ln769_2_fu_887_p3 : ap_phi_mux_src_buf_2_1_0_i_i_phi_fu_450_p4);

assign select_ln791_fu_972_p3 = ((icmp_ln891_reg_1268[0:0] === 1'b1) ? select_ln769_fu_873_p3 : ap_phi_mux_src_buf_0_1_0_i_i_phi_fu_414_p4);

assign sext_ln758_fu_623_p1 = $signed(add_ln758_fu_617_p2);

assign tmp_fu_677_p3 = ret_V_1_fu_663_p2[32'd12];

assign trunc_ln1354_fu_669_p1 = ret_V_1_fu_663_p2[12:0];

assign trunc_ln321_1_fu_546_p1 = row_ind_2_V_1_load_reg_1060[1:0];

assign trunc_ln321_2_fu_715_p1 = row_ind_1_V_1_reg_341[1:0];

assign trunc_ln321_3_fu_719_p1 = zero_ind_V_reg_362[1:0];

assign trunc_ln321_4_fu_723_p1 = row_ind_0_V_reg_351[1:0];

assign trunc_ln321_5_fu_779_p1 = tmp_2_fu_768_p5[1:0];

assign trunc_ln321_fu_542_p1 = i_op_assign_1_reg_298[1:0];

assign trunc_ln544_fu_673_p1 = ret_V_1_fu_663_p2[1:0];

assign zext_ln544_1_fu_596_p1 = t_V_reg_330;

assign zext_ln544_2_fu_748_p1 = t_V_3_reg_458;

assign zext_ln544_3_fu_755_p1 = t_V_3_reg_458_pp1_iter1_reg;

assign zext_ln544_fu_567_p1 = t_V_1_reg_318;

assign zext_ln850_fu_522_p1 = p_image_width_read_reg_1048;

assign zext_ln887_1_fu_525_p1 = p_image_width_read_reg_1048;

assign zext_ln887_2_fu_639_p1 = t_V_2_reg_374;

assign zext_ln887_fu_528_p1 = row_ind_2_V_2_fu_106;

always @ (posedge ap_clk) begin
    row_ind_2_V_load_reg_1055[12:2] <= 11'b00000000000;
    row_ind_2_V_1_load_reg_1060[12:2] <= 11'b00000000000;
    row_ind_2_V_2_load_reg_1066[12:2] <= 11'b00000000000;
    zext_ln850_reg_1084[31:12] <= 20'b00000000000000000000;
    zext_ln887_1_reg_1091[12] <= 1'b0;
    zext_ln887_reg_1097[31:2] <= 30'b000000000000000000000000000000;
    empty_12_reg_1173[12] <= 1'b0;
    row_ind_2_V_fu_98[12:2] <= 11'b00000000000;
    row_ind_2_V_1_fu_102[12:2] <= 11'b00000000000;
    row_ind_2_V_2_fu_106[12:2] <= 11'b00000000000;
    row_ind_2_V_3_fu_110[12:2] <= 11'b00000000000;
end

endmodule //xFfastnms5781
